version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "npm"
    directory: "/crates/trusted-server-js/lib"
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "npm"
    directory: "/crates/trusted-server-integration-tests/browser"
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "npm"
    directory: "/crates/trusted-server-integration-tests/fixtures/frameworks/nextjs"
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
    target-branch: "main"
