//! Generates `crates/openrtb/src/generated.rs` from `proto/openrtb.proto`.
//!
//! Run via the wrapper script:
//!
//! ```sh
//! ./crates/openrtb/generate.sh
//! ```
//!
//! Requires `protoc` to be installed.

use std::fs;
use std::path::PathBuf;

// Pull in postprocess() and helpers from the openrtb crate's codegen module.
include!("../../openrtb/src/codegen.rs");

fn main() {
    let openrtb_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../openrtb");
    let proto_path = openrtb_dir.join("proto/openrtb.proto");
    let proto_dir = openrtb_dir.join("proto");
    let output_path = openrtb_dir.join("src/generated.rs");

    // Use a temporary directory for raw prost-build output.
    let tmp = std::env::temp_dir().join("openrtb-codegen");
    fs::create_dir_all(&tmp).expect("should create temp directory");

    // Phase 1: Compile proto with prost-build.
    eprintln!("Compiling {}...", proto_path.display());
    prost_build::Config::new()
        .out_dir(&tmp)
        .compile_protos(
            &[proto_path.to_str().expect("should have valid proto path")],
            &[proto_dir.to_str().expect("should have valid proto dir")],
        )
        .expect("should compile openrtb.proto (is protoc installed?)");

    // Phase 2: Post-process the generated file.
    let raw_path = tmp.join("com.iabtechlab.openrtb.v2.rs");
    let code = fs::read_to_string(&raw_path).expect("should read raw prost output");
    let processed = postprocess(&code);

    // Phase 3: Write the checked-in file with a header.
    let output = format!(
        "\
// @generated by openrtb-codegen from proto/openrtb.proto
// Do not edit manually — run `./crates/openrtb/generate.sh` to regenerate.
// source: proto/openrtb.proto

{processed}"
    );

    fs::write(&output_path, output).expect("should write generated.rs");
    eprintln!("Wrote {}", output_path.display());

    // Clean up temp files.
    let _ = fs::remove_dir_all(&tmp);
}
