[[handlers]]
path = "^/secure"
username = "user"
password = "pass"

[publisher]
domain = "test-publisher.com"
cookie_domain = ".test-publisher.com"
origin_url = "http://tauritutorials.com"
proxy_secret = "change-me-proxy-secret"

[prebid]
server_url = "http://68.183.113.79:8000"
timeout_ms = 1000
bidders = ["kargo", "rubicon", "appnexus", "openx"]
auto_configure = false
debug = false

[permutive]
project_id = ""
workspace_id = "a530f86f-f672-43fc-a11e-64681a09407d"
organization_id = "a9695278-4085-40b3-9f02-8d4c38a6ff01"
auto_configure = true
proxy_events = true
proxy_sync = true
cache_ttl_seconds = 3600

[synthetic]
counter_store = "counter_store"
opid_store = "opid_store"
secret_key = "trusted-server"
# Possible values
#   - "client_ip"
#   - "user_agent"
#   - "first_party_id"
#   - "auth_user_id"
#   - "publisher_domain"
#   - "accept_language"
template = "{{ client_ip }}:{{ user_agent }}:{{ first_party_id }}:{{ auth_user_id }}:{{ publisher_domain }}:{{ accept_language }}"

# Custom headers to be included in every response
[response_headers]
X-Custom-Header = "custom header value"
