# shellcheck shell=bash
# Shared helpers for the documentation proposal scripts. Source this file;
# do not execute it.

DOCS_PROPOSAL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCS_PROPOSAL_ALLOWED_RE='^docs/(guide/.+|index\.md)$'
DOCS_PROPOSAL_MAX_RATIONALE_BYTES=20000

# Exits unless the argument is a full commit SHA reachable from origin/main.
docs_proposal_require_sha() {
  local sha="$1"
  if ! [[ "$sha" =~ ^[0-9a-f]{40}$ ]]; then
    printf '::error::Expected a full 40-character commit SHA, got %s\n' "$sha" >&2
    exit 1
  fi
  if ! git merge-base --is-ancestor "$sha" origin/main 2>/dev/null; then
    printf '::error::Commit %s is not reachable from origin/main\n' "$sha" >&2
    exit 1
  fi
}

docs_proposal_branch() {
  printf 'docs/auto/%s\n' "${1:0:12}"
}

# Reads changed paths on stdin, prints those outside the allowlist, and
# returns 1 when any were found.
docs_proposal_disallowed_paths() {
  local path
  local found=0
  while IFS= read -r path; do
    if [ -n "$path" ] && ! [[ "$path" =~ $DOCS_PROPOSAL_ALLOWED_RE ]]; then
      printf '%s\n' "$path"
      found=1
    fi
  done
  return "$found"
}

# Applies <patch> to the index on a detached checkout of <sha>, then exits
# when it changes paths outside the allowlist.
docs_proposal_apply() {
  local sha="$1"
  local patch="$2"
  local disallowed
  git switch --quiet --detach "$sha"
  git apply --index "$patch"
  if ! disallowed="$(git diff --cached --name-only --no-renames "$sha" | docs_proposal_disallowed_paths)"; then
    printf '::error::Proposal changes paths outside docs/guide/** and docs/index.md:\n%s\n' "$disallowed"
    exit 1
  fi
}

docs_proposal_pr_body() {
  local sha="$1"
  local subject="$2"
  local origin_pr="$3"
  local rationale="$4"
  local origin=""
  if [ -n "$origin_pr" ]; then
    origin=" (#$origin_pr)"
  fi
  printf '<!-- docs-proposal: %s -->\n' "$sha"
  printf 'Proposed documentation update for merged change %s%s: %s\n\n' "$sha" "$origin" "$subject"
  printf 'Generated by GitHub Copilot CLI in the docs-proposal workflow. A maintainer must verify every hunk against the merged code before merging. Each hunk has a review comment citing its source and a suggestion that reverts it.\n\n'
  printf '## Rationale\n\n'
  if [ -s "$rationale" ]; then
    # The rationale is model output; keep it from pinging users or teams.
    head -c "$DOCS_PROPOSAL_MAX_RATIONALE_BYTES" "$rationale" \
      | node "$DOCS_PROPOSAL_DIR/hunks.mjs" sanitize
    printf '\n'
  else
    printf '_Copilot did not provide a rationale._\n'
  fi
}
