#!/usr/bin/env bash
# Opens or updates the pull request for a validated documentation proposal.
#
# Usage: scripts/docs-proposal/publish.sh <merge-sha> <work-dir>
# <work-dir> holds proposal.patch, rationale.md, evidence.json, and base from
# propose.sh. Requires GH_TOKEN with contents and pull-requests write access.
# Run validate.sh first, in a job without write credentials: this script
# re-checks the path allowlist but never builds or executes proposal content.
set -euo pipefail

sha="$1"
work_dir="$(cd "$2" && pwd)"
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(git rev-parse --show-toplevel)"
# shellcheck source=scripts/docs-proposal/lib.sh
source "$here/lib.sh"

cd "$root"
docs_proposal_require_sha "$sha"
branch="$(docs_proposal_branch "$sha")"
base="$(cat "$work_dir/base")"
if ! [[ "$base" =~ ^[0-9a-f]{40}$ ]]; then
  printf '::error::Expected a full base SHA in %s/base, got %s\n' "$work_dir" "$base" >&2
  exit 1
fi

# A closed or merged proposal is a maintainer decision; never reopen or
# recreate it on a retry.
existing="$(gh pr list --head "$branch" --state all --json number,state,body \
  --jq '.[0] | select(.) | "\(.number) \(.state) \([.body | match("<!-- docs-proposal-base: ([0-9a-f]{40}) -->").captures[0].string] | first // "")"')"
read -r pr_number pr_state pr_base <<< "$existing" || true
if [ -n "$existing" ] && [ "$pr_state" != "OPEN" ]; then
  printf 'Proposal #%s for %s is %s; not reopening it.\n' "$pr_number" "$sha" "$pr_state"
  exit 0
fi

# A retry that inspected a different range, such as a manual dispatch without
# the base of a multi-commit push, must not narrow or close the proposal.
if [ -n "$existing" ] && [ "$pr_base" != "$base" ]; then
  printf '::error::Proposal #%s for %s covers %s..%s, but this run inspected %s..%s. Rerun the workflow with base %s.\n' \
    "$pr_number" "$sha" "${pr_base:-an unrecorded base}" "$sha" "$base" "$sha" "${pr_base:-<original base>}" >&2
  exit 1
fi

# Maintainers push to the proposal branch, and applying a review suggestion
# commits there too. Never overwrite or delete commits beyond the generated
# proposal, whose only parent is the merge commit.
remote_head=""
if git fetch --quiet origin "refs/heads/$branch" 2>/dev/null; then
  remote_head="$(git rev-parse FETCH_HEAD)"
fi
if [ -n "$remote_head" ] && [ "$(git rev-parse "$remote_head^")" != "$sha" ]; then
  printf '::warning::Proposal branch %s has commits beyond the generated proposal; not overwriting it.\n' "$branch"
  exit 0
fi

if [ ! -s "$work_dir/proposal.patch" ]; then
  printf 'No documentation changes proposed for %s.\n' "$sha"
  if [ -n "$existing" ]; then
    gh pr close "$pr_number" --delete-branch \
      --comment "A rerun for $sha proposed no documentation changes."
  fi
  exit 0
fi

docs_proposal_apply "$sha" "$work_dir/proposal.patch"

git -c user.name='github-actions[bot]' \
  -c user.email='41898282+github-actions[bot]@users.noreply.github.com' \
  commit --quiet --no-verify \
  -m "Propose documentation updates for ${sha:0:12}" \
  -m "Generated by the docs-proposal workflow from $sha."
head_sha="$(git rev-parse HEAD)"

# An identical tree means a previous run already pushed this proposal. Reuse
# its commit instead of pushing, so a retry resumes any pull request or review
# step that failed after the push. The lease refuses the push if the branch
# moved after it was fetched.
if [ -n "$remote_head" ] && [ "$(git rev-parse "$remote_head^{tree}")" = "$(git rev-parse 'HEAD^{tree}')" ]; then
  head_sha="$remote_head"
  printf 'Proposal branch for %s is unchanged; not pushing.\n' "$sha"
else
  git push --quiet --force-with-lease="refs/heads/$branch:$remote_head" origin "HEAD:refs/heads/$branch"
fi

subject="$(git log -1 --format=%s "$sha")"
origin_pr="$(gh api "repos/{owner}/{repo}/commits/$sha/pulls" --jq '.[0].number // empty' || true)"
title="$(printf 'Update documentation for %s' "$subject" | cut -c1-200)"
docs_proposal_pr_body "$sha" "$base" "$subject" "$origin_pr" "$work_dir/rationale.md" > "$work_dir/pr-body.md"
if [ -n "$existing" ]; then
  gh pr edit "$pr_number" --title "$title" --body-file "$work_dir/pr-body.md"
else
  pr_url="$(gh pr create --base main --head "$branch" --title "$title" --body-file "$work_dir/pr-body.md")"
  pr_number="${pr_url##*/}"
fi

# Skip the review when this commit already has one, so retries never post
# duplicate comments.
posted_review="$(gh api --paginate "repos/{owner}/{repo}/pulls/$pr_number/reviews" \
  --jq ".[] | select(.commit_id == \"$head_sha\" and .user.login == \"github-actions[bot]\") | .id")"
if [ -n "$posted_review" ]; then
  printf 'Proposal #%s for %s is already published.\n' "$pr_number" "$sha"
  exit 0
fi

git diff --no-renames "$sha" "$head_sha" -- docs \
  | node "$here/hunks.mjs" review "$work_dir/evidence.json" "$head_sha" > "$work_dir/review.json"
gh api --method POST "repos/{owner}/{repo}/pulls/$pr_number/reviews" --input "$work_dir/review.json" > /dev/null
printf 'Published proposal #%s for %s.\n' "$pr_number" "$sha"
