#!/usr/bin/env bash
# Validates a documentation proposal and opens or updates its pull request.
#
# Usage: scripts/docs-proposal/publish.sh <merge-sha> <work-dir>
# <work-dir> holds proposal.patch, rationale.md, and evidence.json from
# propose.sh. Requires GH_TOKEN with contents and pull-requests write access.
set -euo pipefail

sha="$1"
work_dir="$(cd "$2" && pwd)"
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(git rev-parse --show-toplevel)"
# shellcheck source=scripts/docs-proposal/lib.sh
source "$here/lib.sh"

cd "$root"
docs_proposal_require_sha "$sha"
branch="$(docs_proposal_branch "$sha")"

# A closed or merged proposal is a maintainer decision; never reopen or
# recreate it on a retry.
existing="$(gh pr list --head "$branch" --state all --json number,state --jq '.[0] | select(.) | "\(.number) \(.state)"')"
pr_number="${existing%% *}"
pr_state="${existing#* }"
if [ -n "$existing" ] && [ "$pr_state" != "OPEN" ]; then
  printf 'Proposal #%s for %s is %s; not reopening it.\n' "$pr_number" "$sha" "$pr_state"
  exit 0
fi

if [ ! -s "$work_dir/proposal.patch" ]; then
  printf 'No documentation changes proposed for %s.\n' "$sha"
  if [ -n "$existing" ]; then
    gh pr close "$pr_number" --delete-branch \
      --comment "A rerun for $sha proposed no documentation changes."
  fi
  exit 0
fi

git switch --quiet --detach "$sha"
git apply --index "$work_dir/proposal.patch"
if ! disallowed="$(git diff --cached --name-only --no-renames "$sha" | docs_proposal_disallowed_paths)"; then
  printf '::error::Proposal changes paths outside docs/guide/** and docs/index.md:\n%s\n' "$disallowed"
  exit 1
fi

(cd docs && npm ci && npm run lint && npm run format && npm run build)

git -c user.name='github-actions[bot]' \
  -c user.email='41898282+github-actions[bot]@users.noreply.github.com' \
  commit --quiet --no-verify \
  -m "Propose documentation updates for ${sha:0:12}" \
  -m "Generated by the docs-proposal workflow from $sha."
head_sha="$(git rev-parse HEAD)"

# An identical tree means this is a retry of an already-published proposal;
# skip the push and review so reviewers do not see duplicate comments.
remote_tree=""
if git fetch --quiet origin "refs/heads/$branch" 2>/dev/null; then
  remote_tree="$(git rev-parse 'FETCH_HEAD^{tree}')"
fi
if [ -n "$existing" ] && [ "$remote_tree" = "$(git rev-parse 'HEAD^{tree}')" ]; then
  printf 'Proposal #%s for %s is unchanged.\n' "$pr_number" "$sha"
  exit 0
fi
git push --quiet --force origin "HEAD:refs/heads/$branch"

subject="$(git log -1 --format=%s "$sha")"
origin_pr="$(gh api "repos/{owner}/{repo}/commits/$sha/pulls" --jq '.[0].number // empty' || true)"
title="$(printf 'Update documentation for %s' "$subject" | cut -c1-200)"
docs_proposal_pr_body "$sha" "$subject" "$origin_pr" "$work_dir/rationale.md" > "$work_dir/pr-body.md"
if [ -n "$existing" ]; then
  gh pr edit "$pr_number" --title "$title" --body-file "$work_dir/pr-body.md"
else
  pr_url="$(gh pr create --base main --head "$branch" --title "$title" --body-file "$work_dir/pr-body.md")"
  pr_number="${pr_url##*/}"
fi

git diff --no-renames "$sha" "$head_sha" -- docs \
  | node "$here/hunks.mjs" review "$work_dir/evidence.json" "$head_sha" > "$work_dir/review.json"
gh api --method POST "repos/{owner}/{repo}/pulls/$pr_number/reviews" --input "$work_dir/review.json" > /dev/null
printf 'Published proposal #%s for %s.\n' "$pr_number" "$sha"
