//! Trusted Server tsjs — embedded JS bundle produced from the TypeScript project in `ts/`.
//!
//! - The `build.rs` runs `npm run build` in `ts/` (if available) to output `dist/tsjs.js`.
//! - This crate embeds `dist/tsjs.js` so other Rust crates can serve it.

/// File name recommended when serving the JS.
pub const TSJS_FILENAME: &str = "tsjs.js";

/// The JavaScript bundle contents generated by the build script into OUT_DIR.
pub const TSJS_BUNDLE: &str = include_str!(concat!(env!("OUT_DIR"), "/tsjs.js"));

/// Convenience accessor for the JS bundle.
pub fn js() -> &'static str {
    TSJS_BUNDLE
}
