//! Trusted Server tsjs — embedded JS bundle produced from the TypeScript project in `ts/`.
//!
//! - The `build.rs` runs `npm run build` in `ts/` (if available) to output `dist/tsjs-core.js` and `dist/tsjs-ext.js`.
//! - This crate embeds `dist/tsjs-core.js` (core) and `dist/tsjs-ext.js` (optional extension) so other Rust crates can serve them.

/// File name recommended when serving the JS.
pub const TSJS_CORE_FILENAME: &str = "tsjs-core.js";
pub const TSJS_EXT_FILENAME: &str = "tsjs-ext.js";

/// The JavaScript bundle contents generated by the build script into OUT_DIR.
pub const TSJS_CORE_BUNDLE: &str = include_str!(concat!(env!("OUT_DIR"), "/tsjs-core.js"));
pub const TSJS_EXT_BUNDLE: &str = include_str!(concat!(env!("OUT_DIR"), "/tsjs-ext.js"));
