#![allow(
    clippy::expect_used,
    clippy::panic,
    reason = "build script failures should stop Cargo with a clear diagnostic"
)]

use std::cmp::Ordering;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitStatus};

use build_print::{info, warn};
use sha2::{Digest as _, Sha256};

fn main() {
    // Rebuild if TS sources change (belt-and-suspenders): enumerate every file under lib/
    println!("cargo:rerun-if-changed=lib");
    watch_dir_recursively(Path::new("lib"));

    // Allow opt-out or force via env
    let skip = env::var("TSJS_SKIP_BUILD").is_ok_and(|value| value == "1");

    let crate_dir = PathBuf::from(
        env::var("CARGO_MANIFEST_DIR").expect("should set CARGO_MANIFEST_DIR for build script"),
    );
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("should set OUT_DIR for build script"));
    let ts_dir = crate_dir.join("lib");
    let dist_dir = crate_dir.join("dist");

    // Ensure dist exists
    fs::create_dir_all(&dist_dir).expect("should create dist directory");

    // Only try to build if we have a library project
    if !ts_dir.join("package.json").exists() {
        // No TS project; rely on prebuilt dist if present
        return;
    }

    // If Node/npm is absent, keep going if dist exists
    let npm = which::which("npm").ok();
    if npm.is_none() {
        warn!("tsjs: npm not found; will use existing dist if available");
    }

    // Install deps if node_modules missing
    if !skip
        && let Some(npm_path) = npm.as_deref()
        && !ts_dir.join("node_modules").exists()
    {
        let status = Command::new(npm_path)
            .arg("ci")
            .current_dir(&ts_dir)
            .status();
        if !status.as_ref().is_ok_and(ExitStatus::success) {
            warn!("tsjs: npm ci failed; using existing dist if available");
        }
    }

    // Run tests if requested
    if !skip
        && env::var("TSJS_TEST").is_ok_and(|value| value == "1")
        && let Some(npm_path) = npm.as_deref()
    {
        Command::new(npm_path)
            .args(["run", "test", "--", "--run"])
            .current_dir(&ts_dir)
            .status()
            .expect("should run requested TSJS tests");
    }

    // Build all module files
    if !skip && let Some(npm_path) = npm.as_deref() {
        info!("tsjs: Building per-module bundles");

        let status = Command::new(npm_path)
            .args(["run", "build"])
            .current_dir(&ts_dir)
            .status();
        assert!(
            status.as_ref().is_ok_and(ExitStatus::success),
            "tsjs: npm run build failed - refusing to use stale bundles"
        );
    }

    embed_trace_assets(&ts_dir, &dist_dir, &out_dir, !skip && npm.is_some());

    // Discover all tsjs-*.js files in dist/
    let mut modules: Vec<(String, String)> = Vec::new(); // (id, filename)
    if let Ok(entries) = fs::read_dir(&dist_dir) {
        for entry in entries.flatten() {
            let filename = entry.file_name().to_string_lossy().to_string();
            if let Some(id) = filename
                .strip_prefix("tsjs-")
                .and_then(|stem| stem.strip_suffix(".js"))
            {
                modules.push((id.to_owned(), filename));
            }
        }
    }

    // Sort alphabetically but ensure "core" is always first
    modules.sort_by(|left, right| {
        if left.0 == "core" {
            Ordering::Less
        } else if right.0 == "core" {
            Ordering::Greater
        } else {
            left.0.cmp(&right.0)
        }
    });

    assert!(
        !modules.is_empty(),
        "tsjs: no tsjs-*.js files found in {}. Ensure `npm run build` succeeds.",
        dist_dir.display()
    );

    info!(
        "tsjs: Discovered {} module files: {:?}",
        modules.len(),
        modules
            .iter()
            .map(|(id, _)| id.as_str())
            .collect::<Vec<_>>()
    );

    // Copy each module file to OUT_DIR
    for (_, filename) in &modules {
        copy_bundle(filename, true, &dist_dir, &out_dir);
    }

    // Generate tsjs_modules.rs with include_str!() for each module
    let mut codegen = String::new();
    codegen.push_str("// Auto-generated by build.rs - DO NOT EDIT\n\n");

    writeln!(
        codegen,
        "pub(crate) const TSJS_MODULES: [TsjsModuleMeta; {}] = [",
        modules.len()
    )
    .expect("should write generated module header");
    for (id, filename) in &modules {
        let sha256 = bundle_sha256(&out_dir.join(filename));
        writeln!(
            codegen,
            "    TsjsModuleMeta {{\n        bundle: include_str!(concat!(env!(\"OUT_DIR\"), \"/{filename}\")),\n        id: \"{id}\",\n        sha256: \"{sha256}\",\n    }},\n"
        )
        .expect("should write generated module entry");
    }
    codegen.push_str("];\n");
    writeln!(
        codegen,
        "pub(crate) const ALL_MODULE_IDS: [&str; {0}] = {{\n    let mut ids = [\"\"; {0}];\n    let mut index = 0;\n    while index < {0} {{\n        ids[index] = TSJS_MODULES[index].id;\n        index += 1;\n    }}\n    ids\n}};",
        modules.len()
    )
    .expect("should write generated module IDs");
    codegen.push_str("\npub(crate) struct TsjsModuleMeta {\n");
    codegen.push_str("    pub bundle: &'static str,\n");
    codegen.push_str("    pub id: &'static str,\n");
    codegen.push_str("    pub sha256: &'static str,\n");
    codegen.push_str("}\n");

    let generated_path = out_dir.join("tsjs_modules.rs");
    fs::write(&generated_path, &codegen).unwrap_or_else(|err| {
        panic!(
            "tsjs: failed to write generated code to {}: {err}",
            generated_path.display()
        );
    });
}

fn embed_trace_assets(ts_dir: &Path, dist_dir: &Path, out_dir: &Path, rebuilt: bool) {
    let manifest: serde_json::Value = serde_json::from_slice(
        &fs::read(ts_dir.join("trace-assets-manifest.json"))
            .expect("should read the committed trace asset manifest"),
    )
    .expect("should parse the trace asset manifest");
    let object = manifest
        .as_object()
        .expect("should use a trace manifest object");
    assert!(
        object.len() == 3
            && object.contains_key("schema_version")
            && object.contains_key("assets")
            && object.contains_key("source_sha256"),
        "tsjs: trace manifest must contain exactly the documented fields"
    );
    assert_eq!(
        manifest["schema_version"].as_u64(),
        Some(1),
        "tsjs: trace manifest schema version must be one"
    );
    assert_eq!(
        manifest["source_sha256"].as_str(),
        Some(trace_source_digest(ts_dir).as_str()),
        "tsjs: trace build inputs changed; rebuild and review the unpublished versioned assets"
    );
    let assets = manifest["assets"]
        .as_array()
        .expect("should list the versioned trace assets");
    assert_eq!(
        assets.len(),
        2,
        "tsjs: version one requires its JS and CSS assets"
    );
    let mut generated = String::from("const TRACE_ASSETS: [TraceAsset; 2] = [\n");
    for (asset, file) in assets.iter().zip(["v1.js", "v1.css"]) {
        let fields = asset
            .as_object()
            .expect("should represent trace asset metadata as an object");
        assert!(
            fields.len() == 3
                && fields.contains_key("path")
                && fields.contains_key("file")
                && fields.contains_key("sha256"),
            "tsjs: trace asset metadata must contain exactly path, file and sha256"
        );
        let path = format!("/_ts/trace/assets/{file}");
        assert_eq!(
            asset["path"].as_str(),
            Some(path.as_str()),
            "tsjs: trace asset path must be exact"
        );
        assert_eq!(
            asset["file"].as_str(),
            Some(file),
            "tsjs: trace asset filename must be exact"
        );
        let content = fs::read(ts_dir.join("trace-assets").join(file))
            .expect("should read the committed versioned trace asset bytes");
        let digest = hex::encode(Sha256::digest(&content));
        assert_eq!(
            asset["sha256"].as_str(),
            Some(digest.as_str()),
            "tsjs: committed trace asset bytes do not match their manifest digest"
        );
        if rebuilt {
            assert_eq!(
                fs::read(dist_dir.join("trace").join(file))
                    .expect("should rebuild both versioned trace assets"),
                content,
                "tsjs: rebuilt trace bytes differ from committed assets; review the unpublished draft or add a version"
            );
        }
        fs::write(out_dir.join(format!("trace-{file}")), &content)
            .expect("should copy verified trace bytes into the build output");
        writeln!(generated,
            "TraceAsset {{ path: \"{path}\", bytes: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/trace-{file}\")), sha256: \"{digest}\" }},")
            .expect("should generate the verified trace asset entry");
    }
    generated.push_str("];\n");
    fs::write(out_dir.join("trace_assets.rs"), generated)
        .expect("should generate the trace asset lookup table");
}

fn trace_source_digest(ts_dir: &Path) -> String {
    let mut sources = vec![
        "build-all.mjs".to_owned(),
        "trace-asset-sources.mjs".to_owned(),
        "package-lock.json".to_owned(),
    ];
    let mut directories = vec![PathBuf::from("src/trace")];
    while let Some(directory) = directories.pop() {
        for entry in
            fs::read_dir(ts_dir.join(&directory)).expect("should enumerate trace build inputs")
        {
            let entry = entry.expect("should read a trace build input entry");
            let relative = directory.join(entry.file_name());
            let kind = entry
                .file_type()
                .expect("should inspect the trace build input type");
            if kind.is_dir() {
                directories.push(relative);
            } else if kind.is_file()
                && relative
                    .extension()
                    .is_some_and(|extension| extension == "ts" || extension == "css")
            {
                sources.push(
                    relative
                        .to_str()
                        .expect("should use UTF-8 trace build input filenames")
                        .replace('\\', "/"),
                );
            }
        }
    }
    sources.sort();
    let mut hash = Sha256::new();
    for source in sources {
        hash.update(source.as_bytes());
        hash.update([0]);
        hash.update(fs::read(ts_dir.join(&source)).expect("should read a trace build input"));
        hash.update([0]);
    }
    hex::encode(hash.finalize())
}

fn bundle_sha256(path: &Path) -> String {
    let content = fs::read(path).unwrap_or_else(|err| {
        panic!(
            "tsjs: failed to read copied bundle {} for hashing: {err}",
            path.display()
        );
    });
    hex::encode(Sha256::digest(&content))
}

fn copy_bundle(filename: &str, required: bool, dist_dir: &Path, out_dir: &Path) {
    let source = dist_dir.join(filename);
    let target = out_dir.join(filename);

    if source.exists() {
        if let Err(err) = fs::copy(&source, &target) {
            assert!(
                !required,
                "tsjs: failed to copy {} to {}: {err}",
                source.display(),
                target.display()
            );
        }
        return;
    }

    assert!(
        !required,
        "tsjs: bundle {filename} not found: {}. Ensure Node is installed and `npm run build` succeeds, or commit dist/{filename}.",
        source.display()
    );

    fs::write(&target, "").expect("should write optional empty bundle placeholder");
}

fn watch_dir_recursively(root: &Path) {
    if !root.exists() {
        return;
    }
    let mut stack = vec![root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let Ok(read) = fs::read_dir(&dir) else {
            continue;
        };
        for entry in read.flatten() {
            let path = entry.path();
            // Always ask Cargo to rerun if this path changes
            if let Some(path_str) = path.to_str() {
                println!("cargo:rerun-if-changed={path_str}");
            }
            if path.is_dir() {
                stack.push(path);
            }
        }
    }
}
