#![allow(
    clippy::expect_used,
    clippy::panic,
    reason = "build script failures should stop Cargo with a clear diagnostic"
)]

use std::cmp::Ordering;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitStatus};

use build_print::{info, warn};
use sha2::{Digest as _, Sha256};

const RELEASE_SENTINEL: &str = "__TSJS_RELEASE_ID_SENTINEL_V1__";
const RELEASE_PREFIX: &[u8] = b"tsjs-release-v1\0";

fn main() {
    // Rebuild if TS sources change (belt-and-suspenders): enumerate every file under lib/
    println!("cargo:rerun-if-changed=lib");
    watch_dir_recursively(Path::new("lib"));

    // Allow opt-out or force via env
    let skip = env::var("TSJS_SKIP_BUILD").is_ok_and(|value| value == "1");

    let crate_dir = PathBuf::from(
        env::var("CARGO_MANIFEST_DIR").expect("should set CARGO_MANIFEST_DIR for build script"),
    );
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("should set OUT_DIR for build script"));
    let ts_dir = crate_dir.join("lib");
    let dist_dir = crate_dir.join("dist");

    // Ensure dist exists
    fs::create_dir_all(&dist_dir).expect("should create dist directory");

    // Only try to build if we have a library project
    if !ts_dir.join("package.json").exists() {
        // No TS project; rely on prebuilt dist if present
        return;
    }

    // If Node/npm is absent, keep going if dist exists
    let npm = which::which("npm").ok();
    if npm.is_none() {
        warn!("tsjs: npm not found; will use existing dist if available");
    }

    // Install deps if node_modules missing
    if !skip
        && let Some(npm_path) = npm.as_deref()
        && !ts_dir.join("node_modules").exists()
    {
        let status = Command::new(npm_path)
            .arg("ci")
            .current_dir(&ts_dir)
            .status();
        if !status.as_ref().is_ok_and(ExitStatus::success) {
            warn!("tsjs: npm ci failed; using existing dist if available");
        }
    }

    // Run tests if requested
    if !skip
        && env::var("TSJS_TEST").is_ok_and(|value| value == "1")
        && let Some(npm_path) = npm.as_deref()
    {
        Command::new(npm_path)
            .args(["run", "test", "--", "--run"])
            .current_dir(&ts_dir)
            .status()
            .expect("should run requested TSJS tests");
    }

    // Build all module files
    if !skip && let Some(npm_path) = npm.as_deref() {
        info!("tsjs: Building per-module bundles");

        let status = Command::new(npm_path)
            .args(["run", "build"])
            .current_dir(&ts_dir)
            .status();
        assert!(
            status.as_ref().is_ok_and(ExitStatus::success),
            "tsjs: npm run build failed - refusing to use stale bundles"
        );
    }

    // Discover all tsjs-*.js files in dist/
    let mut modules: Vec<(String, String)> = Vec::new(); // (id, filename)
    if let Ok(entries) = fs::read_dir(&dist_dir) {
        for entry in entries.flatten() {
            let filename = entry.file_name().to_string_lossy().to_string();
            if let Some(id) = filename
                .strip_prefix("tsjs-")
                .and_then(|stem| stem.strip_suffix(".js"))
            {
                modules.push((id.to_owned(), filename));
            }
        }
    }

    // Sort alphabetically but ensure "core" is always first
    modules.sort_by(|left, right| {
        if left.0 == "core" {
            Ordering::Less
        } else if right.0 == "core" {
            Ordering::Greater
        } else {
            left.0.cmp(&right.0)
        }
    });

    assert!(
        !modules.is_empty(),
        "tsjs: no tsjs-*.js files found in {}. Ensure `npm run build` succeeds.",
        dist_dir.display()
    );

    let release_id = validate_release(&modules, &dist_dir);
    copy_bundle(
        "gpt-bootstrap-fallback.js",
        true,
        &crate_dir,
        &dist_dir,
        &out_dir,
    );

    info!(
        "tsjs: Discovered {} module files: {:?}",
        modules.len(),
        modules
            .iter()
            .map(|(id, _)| id.as_str())
            .collect::<Vec<_>>()
    );

    // Copy each module file to OUT_DIR
    for (_, filename) in &modules {
        copy_bundle(filename, true, &crate_dir, &dist_dir, &out_dir);
    }

    // Generate tsjs_modules.rs with include_str!() for each module
    let mut codegen = String::new();
    codegen.push_str("// Auto-generated by build.rs - DO NOT EDIT\n\n");
    writeln!(
        codegen,
        "pub(crate) const TSJS_RELEASE_ID: &str = \"{release_id}\";"
    )
    .expect("should write generated release id");
    codegen.push_str(
        "pub(crate) const GPT_BOOTSTRAP_FALLBACK: &str = include_str!(concat!(env!(\"OUT_DIR\"), \"/gpt-bootstrap-fallback.js\"));\n\n",
    );

    writeln!(
        codegen,
        "pub(crate) const TSJS_MODULES: [TsjsModuleMeta; {}] = [",
        modules.len()
    )
    .expect("should write generated module header");
    for (id, filename) in &modules {
        writeln!(
            codegen,
            "    TsjsModuleMeta {{\n        bundle: include_str!(concat!(env!(\"OUT_DIR\"), \"/{filename}\")),\n        id: \"{id}\",\n    }},\n"
        )
        .expect("should write generated module entry");
    }
    codegen.push_str("];\n");
    codegen.push_str("\npub(crate) struct TsjsModuleMeta {\n");
    codegen.push_str("    pub bundle: &'static str,\n");
    codegen.push_str("    pub id: &'static str,\n");
    codegen.push_str("}\n");

    let generated_path = out_dir.join("tsjs_modules.rs");
    fs::write(&generated_path, &codegen).unwrap_or_else(|err| {
        panic!(
            "tsjs: failed to write generated code to {}: {err}",
            generated_path.display()
        );
    });
}

fn validate_release(modules: &[(String, String)], dist_dir: &Path) -> String {
    let bundles = modules
        .iter()
        .map(|(id, filename)| format!(r#"{{"id":"{id}","file":"{filename}"}}"#))
        .collect::<Vec<_>>()
        .join(",");
    let manifest = fs::read_to_string(dist_dir.join("tsjs-release-v1.json"))
        .expect("should read generated release manifest");
    let manifest_prefix = r#"{"version":1,"releaseId":""#;
    let manifest_value = manifest
        .strip_prefix(manifest_prefix)
        .expect("should use exact release manifest prefix");
    let release_id = manifest_value
        .get(..64)
        .expect("should contain a 64-character release id")
        .to_owned();
    assert!(
        release_id
            .bytes()
            .all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase()),
        "tsjs: generated manifest has invalid release id"
    );
    let expected_manifest = format!(
        r#"{{"version":1,"releaseId":"{release_id}","bundles":[{bundles}]}}
"#
    );
    assert_eq!(
        manifest, expected_manifest,
        "tsjs: generated release manifest disagrees"
    );

    let mut canonical = Vec::new();
    canonical.extend_from_slice(RELEASE_PREFIX);
    for (id, filename) in modules {
        let source = fs::read_to_string(dist_dir.join(filename))
            .unwrap_or_else(|error| panic!("tsjs: failed to read {filename}: {error}"));
        assert_eq!(
            source.matches(&release_id).count(),
            1,
            "tsjs: bundle {filename} must contain its release id exactly once"
        );
        let normalized = source.replacen(&release_id, RELEASE_SENTINEL, 1);
        canonical.extend_from_slice(id.as_bytes());
        canonical.push(0);
        canonical.extend_from_slice(normalized.len().to_string().as_bytes());
        canonical.push(0);
        canonical.extend_from_slice(normalized.as_bytes());
        canonical.push(0);
    }
    let computed = Sha256::digest(&canonical)
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<String>();
    assert_eq!(
        computed, release_id,
        "tsjs: sentinel-normalized release hash mismatch"
    );

    let fallback = fs::read_to_string(dist_dir.join("gpt-bootstrap-fallback.js"))
        .expect("should read generated fallback artifact");
    assert!(
        !fallback.contains(RELEASE_SENTINEL),
        "tsjs: fallback sentinel remains"
    );
    assert_eq!(
        fallback.matches(&release_id).count(),
        1,
        "tsjs: fallback artifact must carry the release id exactly once"
    );
    release_id
}

fn copy_bundle(filename: &str, required: bool, crate_dir: &Path, dist_dir: &Path, out_dir: &Path) {
    let primary = dist_dir.join(filename);
    let fallback = crate_dir.join("dist").join(filename);
    let target = out_dir.join(filename);

    for source in [&primary, &fallback] {
        if source.exists() {
            if let Err(err) = fs::copy(source, &target) {
                assert!(
                    !required,
                    "tsjs: failed to copy {} to {}: {err}",
                    source.display(),
                    target.display()
                );
            }
            return;
        }
    }

    assert!(
        !required,
        "tsjs: bundle {filename} not found: {} (and fallback {}). Ensure Node is installed and `npm run build` succeeds, or commit dist/{filename}.",
        primary.display(),
        fallback.display()
    );

    fs::write(&target, "").expect("should write optional empty bundle placeholder");
}

fn watch_dir_recursively(root: &Path) {
    if !root.exists() {
        return;
    }
    let mut stack = vec![root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let Ok(read) = fs::read_dir(&dir) else {
            continue;
        };
        for entry in read.flatten() {
            let path = entry.path();
            // Always ask Cargo to rerun if this path changes
            if let Some(path_str) = path.to_str() {
                println!("cargo:rerun-if-changed={path_str}");
            }
            if path.is_dir() {
                stack.push(path);
            }
        }
    }
}
