//! Auction request/response format conversions.
//!
//! This module handles:
//! - Parsing incoming tsjs/Prebid.js format requests
//! - Converting internal auction results to `OpenRTB` 2.x responses

use edgezero_core::body::Body as EdgeBody;
use error_stack::{ensure, Report, ResultExt};
use http::{header, HeaderValue, Request, Response, StatusCode};
use serde::Deserialize;
use serde_json::Value as JsonValue;
use std::collections::HashMap;
use uuid::Uuid;

use crate::auction::context::ContextValue;
use crate::consent::ConsentContext;
use crate::constants::{HEADER_X_TS_EC, HEADER_X_TS_EC_FRESH};
use crate::creative;
use crate::edge_cookie::generate_ec_id;
use crate::error::TrustedServerError;
use crate::openrtb::{to_openrtb_i32, OpenRtbBid, OpenRtbResponse, ResponseExt, SeatBid, ToExt};
use crate::platform::{GeoInfo, RuntimeServices};
use crate::settings::Settings;

use super::orchestrator::OrchestrationResult;
use super::types::{
    AdFormat, AdSlot, AuctionRequest, DeviceInfo, MediaType, OrchestratorExt, ProviderSummary,
    PublisherInfo, SiteInfo, UserInfo,
};

/// Request body format for auction endpoints (tsjs/Prebid.js format).
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AdRequest {
    pub ad_units: Vec<AdUnit>,
    pub config: Option<JsonValue>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AdUnit {
    pub code: String,
    pub media_types: Option<MediaTypes>,
    pub bids: Option<Vec<BidConfig>>,
}

/// Bidder configuration from the request.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BidConfig {
    pub bidder: String,
    #[serde(default)]
    pub params: serde_json::Value,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MediaTypes {
    pub banner: Option<BannerUnit>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BannerUnit {
    pub sizes: Vec<Vec<u32>>,
}

/// Convert tsjs/Prebid.js request format to internal [`AuctionRequest`].
///
/// The `consent` parameter carries decoded consent signals extracted from the
/// incoming request's cookies and headers. It is populated by the caller
/// (the `/auction` endpoint handler) and forwarded through to the
/// [`OpenRTB`][`crate::openrtb::OpenRtbRequest`] bid request.
///
/// The `ec_id` is generated by the caller before the consent pipeline
/// runs, so that KV Store operations can use it as a key.
///
/// # Errors
///
/// Returns an error if:
/// - Fresh EC ID generation fails
/// - Request contains invalid banner sizes (must be [width, height])
pub fn convert_tsjs_to_auction_request(
    body: &AdRequest,
    settings: &Settings,
    services: &RuntimeServices,
    req: &Request<EdgeBody>,
    consent: ConsentContext,
    ec_id: &str,
    geo: Option<GeoInfo>,
) -> Result<AuctionRequest, Report<TrustedServerError>> {
    let ec_id = ec_id.to_owned();
    let fresh_id =
        generate_ec_id(settings, services).change_context(TrustedServerError::Auction {
            message: "Failed to generate fresh EC ID".to_string(),
        })?;

    // Convert ad units to slots
    let mut slots = Vec::new();
    for unit in &body.ad_units {
        if let Some(media_types) = &unit.media_types {
            if let Some(banner) = &media_types.banner {
                let mut formats = Vec::new();
                for size in &banner.sizes {
                    ensure!(
                        size.len() == 2,
                        TrustedServerError::BadRequest {
                            message: "Invalid banner size; expected [width, height]".to_string(),
                        }
                    );

                    formats.push(AdFormat {
                        width: size[0],
                        height: size[1],
                        media_type: MediaType::Banner,
                    });
                }

                // Extract bidder params from the bids array
                let mut bidders = HashMap::new();
                if let Some(bids) = &unit.bids {
                    for bid in bids {
                        bidders.insert(bid.bidder.clone(), bid.params.clone());
                    }
                }

                slots.push(AdSlot {
                    id: unit.code.clone(),
                    formats,
                    floor_price: None,
                    targeting: HashMap::new(),
                    bidders,
                });
            }
        }
    }

    // Build device info with user-agent (always) and geo (if available)
    let device = Some(DeviceInfo {
        user_agent: req
            .headers()
            .get(header::USER_AGENT)
            .and_then(|value| value.to_str().ok())
            .map(str::to_string),
        ip: services.client_info.client_ip.map(|ip| ip.to_string()),
        geo,
    });

    // Forward allowed config entries from the JS request into the context map.
    // Only keys listed in `auction.allowed_context_keys` are accepted;
    // unrecognised keys are silently dropped to prevent injection of
    // arbitrary data by a malicious client payload.
    let mut context = HashMap::new();
    if let Some(ref config) = body.config {
        if let Some(obj) = config.as_object() {
            for (key, value) in obj {
                if settings.auction.allowed_context_keys.contains(key) {
                    match serde_json::from_value::<ContextValue>(value.clone()) {
                        Ok(cv) => {
                            context.insert(key.clone(), cv);
                        }
                        Err(_) => {
                            log::debug!(
                                "Auction context: dropping key '{}' with unsupported type",
                                key
                            );
                        }
                    }
                } else {
                    log::debug!("Auction context: dropping disallowed key '{}'", key);
                }
            }
            if !context.is_empty() {
                log::debug!(
                    "Auction request context: {} entries ({})",
                    context.len(),
                    context.keys().cloned().collect::<Vec<_>>().join(", ")
                );
            }
        }
    }

    Ok(AuctionRequest {
        id: Uuid::new_v4().to_string(),
        slots,
        publisher: PublisherInfo {
            domain: settings.publisher.domain.clone(),
            page_url: Some(format!("https://{}", settings.publisher.domain)),
        },
        user: UserInfo {
            id: ec_id,
            fresh_id,
            consent: Some(consent),
        },
        device,
        site: Some(SiteInfo {
            domain: settings.publisher.domain.clone(),
            page: format!("https://{}", settings.publisher.domain),
        }),
        context,
    })
}

/// Convert `OrchestrationResult` to `OpenRTB` response format.
///
/// Returns rewritten creative HTML directly in the `adm` field for inline delivery.
///
/// # Errors
///
/// Returns an error if:
/// - A winning bid is missing a price
/// - The response serialization fails
pub fn convert_to_openrtb_response(
    result: &OrchestrationResult,
    settings: &Settings,
    auction_request: &AuctionRequest,
) -> Result<Response<EdgeBody>, Report<TrustedServerError>> {
    // Build OpenRTB-style seatbid array
    let mut seatbids = Vec::with_capacity(result.winning_bids.len());

    for (slot_id, bid) in &result.winning_bids {
        let price = bid.price.ok_or_else(|| {
            Report::new(TrustedServerError::Auction {
                message: format!(
                    "Winning bid for slot '{}' from '{}' has no decoded price",
                    slot_id, bid.bidder
                ),
            })
        })?;

        let bid_context = format!(
            "auction {} slot {} bidder {}",
            auction_request.id, slot_id, bid.bidder
        );
        let width = to_openrtb_i32(bid.width, "width", &bid_context);
        let height = to_openrtb_i32(bid.height, "height", &bid_context);

        // Process creative HTML if present - — sanitize dangerous markup first, then rewrite URLs.
        let creative_html = if let Some(ref raw_creative) = bid.creative {
            let sanitized = creative::sanitize_creative_html(raw_creative);
            let rewritten = creative::rewrite_creative_html(settings, &sanitized);

            log::debug!(
                "Processed creative for auction {} slot {} ({} → {} → {} bytes)",
                auction_request.id,
                slot_id,
                raw_creative.len(),
                sanitized.len(),
                rewritten.len()
            );

            rewritten
        } else {
            // No creative provided (e.g., from mediation layer that returns iframe URLs)
            log::warn!(
                "No creative HTML for auction {} slot {} - mediation should have provided creative",
                auction_request.id,
                slot_id
            );
            String::new()
        };

        let openrtb_bid = OpenRtbBid {
            id: Some(format!("{}-{}", bid.bidder, slot_id)),
            impid: Some(slot_id.to_string()),
            price: Some(price),
            adm: Some(creative_html),
            crid: Some(format!("{}-creative", bid.bidder)),
            w: width,
            h: height,
            adomain: bid.adomain.clone().unwrap_or_default(),
            ..Default::default()
        };

        seatbids.push(SeatBid {
            seat: Some(bid.bidder.clone()),
            bid: vec![openrtb_bid],
            ..Default::default()
        });
    }

    // Determine strategy name for response metadata
    let strategy_name = if settings.auction.has_mediator() {
        "parallel_mediation"
    } else {
        "parallel_only"
    };

    // Build per-provider summaries from the orchestration result
    let provider_details: Vec<ProviderSummary> = result
        .provider_responses
        .iter()
        .map(ProviderSummary::from)
        .collect();

    let response_body = OpenRtbResponse {
        id: Some(auction_request.id.to_string()),
        seatbid: seatbids,
        ext: ResponseExt {
            orchestrator: OrchestratorExt {
                strategy: strategy_name.to_string(),
                providers: result.provider_responses.len(),
                total_bids: result.total_bids(),
                time_ms: result.total_time_ms,
                provider_details,
            },
        }
        .to_ext(),
        ..Default::default()
    };

    let body_bytes =
        serde_json::to_vec(&response_body).change_context(TrustedServerError::Auction {
            message: "Failed to serialize auction response".to_string(),
        })?;

    let mut response = Response::new(EdgeBody::from(body_bytes));
    *response.status_mut() = StatusCode::OK;
    response.headers_mut().insert(
        header::CONTENT_TYPE,
        HeaderValue::from_static("application/json"),
    );
    insert_response_header(
        response.headers_mut(),
        &HEADER_X_TS_EC,
        auction_request.user.id.as_str(),
    )?;
    insert_response_header(
        response.headers_mut(),
        &HEADER_X_TS_EC_FRESH,
        auction_request.user.fresh_id.as_str(),
    )?;

    Ok(response)
}

fn insert_response_header(
    headers: &mut http::HeaderMap,
    name: &http::HeaderName,
    value: &str,
) -> Result<(), Report<TrustedServerError>> {
    let header_value =
        HeaderValue::from_str(value).change_context(TrustedServerError::InvalidHeaderValue {
            message: format!("Invalid response header value for {name}"),
        })?;
    headers.insert(name.clone(), header_value);
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::auction::{AuctionResponse, Bid};
    use crate::consent::ConsentContext;
    use crate::platform::test_support::noop_services;
    use crate::test_support::tests::{create_test_settings, VALID_SYNTHETIC_ID};
    use edgezero_core::body::Body as EdgeBody;
    use http::{header, Method, Request as HttpRequest, StatusCode};

    fn sample_ad_request() -> AdRequest {
        AdRequest {
            ad_units: vec![AdUnit {
                code: "slot-1".to_string(),
                media_types: Some(MediaTypes {
                    banner: Some(BannerUnit {
                        sizes: vec![vec![300, 250]],
                    }),
                }),
                bids: Some(vec![BidConfig {
                    bidder: "prebid".to_string(),
                    params: serde_json::json!({"placementId": "abc"}),
                }]),
            }],
            config: None,
        }
    }

    fn sample_auction_request() -> AuctionRequest {
        AuctionRequest {
            id: "auction-123".to_string(),
            slots: vec![AdSlot {
                id: "slot-1".to_string(),
                formats: vec![AdFormat {
                    media_type: MediaType::Banner,
                    width: 300,
                    height: 250,
                }],
                floor_price: None,
                targeting: HashMap::new(),
                bidders: HashMap::new(),
            }],
            publisher: PublisherInfo {
                domain: "publisher.example".to_string(),
                page_url: Some("https://publisher.example/page".to_string()),
            },
            user: UserInfo {
                id: VALID_SYNTHETIC_ID.to_string(),
                fresh_id: "fresh-123".to_string(),
                consent: Some(ConsentContext::default()),
            },
            device: None,
            site: Some(SiteInfo {
                domain: "publisher.example".to_string(),
                page: "https://publisher.example/page".to_string(),
            }),
            context: HashMap::new(),
        }
    }

    #[test]
    fn convert_tsjs_to_auction_request_accepts_http_request() {
        let settings = create_test_settings();
        let req = HttpRequest::builder()
            .method(Method::POST)
            .uri("https://publisher.example/auction")
            .header(header::USER_AGENT, "test-agent")
            .body(EdgeBody::empty())
            .expect("should build request");

        let auction_request = convert_tsjs_to_auction_request(
            &sample_ad_request(),
            &settings,
            &noop_services(),
            &req,
            ConsentContext::default(),
            VALID_SYNTHETIC_ID,
            None,
        )
        .expect("should convert auction request");

        assert_eq!(auction_request.slots.len(), 1, "should create one slot");
        assert_eq!(
            auction_request.slots[0].id, "slot-1",
            "should preserve slot code"
        );
    }

    #[test]
    fn convert_to_openrtb_response_returns_http_response_with_ec_headers() {
        let settings = create_test_settings();
        let bid = Bid {
            slot_id: "slot-1".to_string(),
            price: Some(1.25),
            currency: "USD".to_string(),
            creative: Some("<div>creative</div>".to_string()),
            adomain: Some(vec!["advertiser.example".to_string()]),
            bidder: "prebid".to_string(),
            width: 300,
            height: 250,
            nurl: None,
            burl: None,
            metadata: HashMap::new(),
        };
        let result = OrchestrationResult {
            provider_responses: vec![AuctionResponse::success("prebid", vec![bid.clone()], 12)],
            mediator_response: None,
            winning_bids: HashMap::from([(String::from("slot-1"), bid)]),
            total_time_ms: 12,
            metadata: HashMap::new(),
        };

        let response = convert_to_openrtb_response(&result, &settings, &sample_auction_request())
            .expect("should convert to openrtb response");

        assert_eq!(response.status(), StatusCode::OK, "should return 200 OK");
        assert_eq!(
            response
                .headers()
                .get(header::CONTENT_TYPE)
                .and_then(|value| value.to_str().ok()),
            Some("application/json"),
            "should return json content type"
        );
        assert_eq!(
            response
                .headers()
                .get(&crate::constants::HEADER_X_TS_EC)
                .and_then(|value| value.to_str().ok()),
            Some(VALID_SYNTHETIC_ID),
            "should include EC ID header"
        );
    }
}
