//! Auction request/response format conversions.
//!
//! This module handles:
//! - Parsing incoming tsjs/Prebid.js format requests
//! - Converting internal auction results to `OpenRTB` 2.x responses

use error_stack::{ensure, Report, ResultExt};
use fastly::http::{header, StatusCode};
use fastly::{Request, Response};
use serde::Deserialize;
use serde_json::Value as JsonValue;
use std::collections::HashMap;
use uuid::Uuid;

use crate::auction::context::ContextValue;
use crate::consent::ConsentContext;
use crate::constants::{HEADER_X_TS_EC_CONSENT, HEADER_X_TS_EIDS, HEADER_X_TS_EIDS_TRUNCATED};
use crate::creative;
use crate::ec::eids::encode_eids_header;
use crate::error::TrustedServerError;
use crate::geo::GeoInfo;
use crate::openrtb::{to_openrtb_i32, OpenRtbBid, OpenRtbResponse, ResponseExt, SeatBid, ToExt};
use crate::settings::Settings;

use super::orchestrator::OrchestrationResult;
use super::types::{
    AdFormat, AdSlot, AuctionRequest, DeviceInfo, MediaType, OrchestratorExt, ProviderSummary,
    PublisherInfo, SiteInfo, UserInfo,
};

/// Request body for `POST /auction` (tsjs / Prebid.js wire format).
///
/// `adUnits` lists the placements to bid on. `config` carries optional
/// context values (e.g. audience segments) filtered through
/// [`auction.allowed_context_keys`][`crate::settings::AuctionConfig::allowed_context_keys`].
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AdRequest {
    pub ad_units: Vec<AdUnit>,
    pub config: Option<JsonValue>,
    pub eids: Option<JsonValue>,
}

/// A single ad placement in an [`AdRequest`].
///
/// `code` identifies the slot (e.g. `"atf_sidebar_ad"`) and becomes the
/// impression ID in the outgoing `OpenRTB` request.
///
/// `bids` is optional. When absent or empty the PBS provider falls back to
/// a stored-request keyed by `code` (`imp.ext.prebid.storedrequest.id`).
/// When present, each entry's params are forwarded inline to PBS as
/// `imp.ext.prebid.bidder.<bidder>`.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AdUnit {
    pub code: String,
    pub media_types: Option<MediaTypes>,
    pub bids: Option<Vec<BidConfig>>,
}

/// Inline bidder params for one SSP within an [`AdUnit`].
///
/// `params` is passed verbatim to the corresponding PBS bidder adapter.
/// When the `bids` array is absent, the slot falls back to PBS stored
/// requests — see [`AdUnit`] for details.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BidConfig {
    pub bidder: String,
    #[serde(default)]
    pub params: serde_json::Value,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MediaTypes {
    pub banner: Option<BannerUnit>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BannerUnit {
    pub sizes: Vec<Vec<u32>>,
}

/// Convert tsjs/Prebid.js request format to internal [`AuctionRequest`].
///
/// The `consent` parameter carries decoded consent signals extracted from the
/// incoming request's cookies and headers. It is populated by the caller
/// (the `/auction` endpoint handler) and forwarded through to the
/// [`OpenRTB`][`crate::openrtb::OpenRtbRequest`] bid request.
///
/// The `ec_id` is generated by the caller before the consent pipeline
/// runs, so that KV Store operations can use it as a key.
///
/// # Errors
///
/// Returns an error if:
/// - Fresh EC ID generation fails
/// - Request contains invalid banner sizes (must be [width, height])
pub fn convert_tsjs_to_auction_request(
    body: &AdRequest,
    settings: &Settings,
    req: &Request,
    consent: ConsentContext,
    ec_id: Option<&str>,
) -> Result<AuctionRequest, Report<TrustedServerError>> {
    let ec_id = ec_id.map(str::to_owned);

    // Convert ad units to slots
    let mut slots = Vec::new();
    for unit in &body.ad_units {
        if let Some(media_types) = &unit.media_types {
            if let Some(banner) = &media_types.banner {
                let mut formats = Vec::new();
                for size in &banner.sizes {
                    ensure!(
                        size.len() == 2,
                        TrustedServerError::BadRequest {
                            message: "Invalid banner size; expected [width, height]".to_string(),
                        }
                    );

                    formats.push(AdFormat {
                        width: size[0],
                        height: size[1],
                        media_type: MediaType::Banner,
                    });
                }

                // Extract bidder params from the bids array
                let mut bidders = HashMap::new();
                if let Some(bids) = &unit.bids {
                    for bid in bids {
                        bidders.insert(bid.bidder.clone(), bid.params.clone());
                    }
                }

                slots.push(AdSlot {
                    id: unit.code.clone(),
                    formats,
                    floor_price: None,
                    targeting: HashMap::new(),
                    bidders,
                });
            }
        }
    }

    // Build device info with user-agent (always) and geo (if available)
    let device = Some(DeviceInfo {
        user_agent: req
            .get_header_str("user-agent")
            .map(std::string::ToString::to_string),
        ip: req.get_client_ip_addr().map(|ip| ip.to_string()),
        #[allow(deprecated)]
        geo: GeoInfo::from_request(req),
    });

    // Forward allowed config entries from the JS request into the context map.
    // Only keys listed in `auction.allowed_context_keys` are accepted;
    // unrecognised keys are silently dropped to prevent injection of
    // arbitrary data by a malicious client payload.
    let mut context = HashMap::new();
    if let Some(ref config) = body.config {
        if let Some(obj) = config.as_object() {
            for (key, value) in obj {
                if settings.auction.allowed_context_keys.contains(key) {
                    match serde_json::from_value::<ContextValue>(value.clone()) {
                        Ok(cv) => {
                            context.insert(key.clone(), cv);
                        }
                        Err(_) => {
                            log::debug!(
                                "Auction context: dropping key '{}' with unsupported type",
                                key
                            );
                        }
                    }
                } else {
                    log::debug!("Auction context: dropping disallowed key '{}'", key);
                }
            }
            if !context.is_empty() {
                log::debug!(
                    "Auction request context: {} entries ({})",
                    context.len(),
                    context.keys().cloned().collect::<Vec<_>>().join(", ")
                );
            }
        }
    }

    Ok(AuctionRequest {
        id: Uuid::new_v4().to_string(),
        slots,
        publisher: PublisherInfo {
            domain: settings.publisher.domain.clone(),
            page_url: Some(format!("https://{}", settings.publisher.domain)),
        },
        user: UserInfo {
            id: ec_id,
            consent: Some(consent),
            eids: None,
        },
        device,
        site: Some(SiteInfo {
            domain: settings.publisher.domain.clone(),
            page: format!("https://{}", settings.publisher.domain),
        }),
        context,
    })
}

/// Convert `OrchestrationResult` to `OpenRTB` response format.
///
/// Returns rewritten creative HTML directly in the `adm` field for inline delivery.
///
/// # Errors
///
/// Returns an error if:
/// - A winning bid is missing a price
/// - The response serialization fails
pub fn convert_to_openrtb_response(
    result: &OrchestrationResult,
    settings: &Settings,
    auction_request: &AuctionRequest,
    ec_allowed: bool,
) -> Result<Response, Report<TrustedServerError>> {
    // Build OpenRTB-style seatbid array
    let mut seatbids = Vec::with_capacity(result.winning_bids.len());

    for (slot_id, bid) in &result.winning_bids {
        let price = bid.price.ok_or_else(|| {
            Report::new(TrustedServerError::Auction {
                message: format!(
                    "Winning bid for slot '{}' from '{}' has no decoded price",
                    slot_id, bid.bidder
                ),
            })
        })?;

        let bid_context = format!(
            "auction {} slot {} bidder {}",
            auction_request.id, slot_id, bid.bidder
        );
        let width = to_openrtb_i32(bid.width, "width", &bid_context);
        let height = to_openrtb_i32(bid.height, "height", &bid_context);

        // Process creative HTML if present - — sanitize dangerous markup first, then rewrite URLs.
        let creative_html = if let Some(ref raw_creative) = bid.creative {
            let sanitized = creative::sanitize_creative_html(raw_creative);
            let rewritten = creative::rewrite_creative_html(settings, &sanitized);

            log::debug!(
                "Processed creative for auction {} slot {} ({} → {} → {} bytes)",
                auction_request.id,
                slot_id,
                raw_creative.len(),
                sanitized.len(),
                rewritten.len()
            );

            rewritten
        } else {
            // No creative provided (e.g., from mediation layer that returns iframe URLs)
            log::warn!(
                "No creative HTML for auction {} slot {} - mediation should have provided creative",
                auction_request.id,
                slot_id
            );
            String::new()
        };

        let openrtb_bid = OpenRtbBid {
            id: Some(format!("{}-{}", bid.bidder, slot_id)),
            impid: Some(slot_id.to_string()),
            price: Some(price),
            adm: Some(creative_html),
            crid: Some(format!("{}-creative", bid.bidder)),
            w: width,
            h: height,
            adomain: bid.adomain.clone().unwrap_or_default(),
            ..Default::default()
        };

        seatbids.push(SeatBid {
            seat: Some(bid.bidder.clone()),
            bid: vec![openrtb_bid],
            ..Default::default()
        });
    }

    // Determine strategy name for response metadata
    let strategy_name = if settings.auction.has_mediator() {
        "parallel_mediation"
    } else {
        "parallel_only"
    };

    // Build per-provider summaries from the orchestration result
    let provider_details: Vec<ProviderSummary> = result
        .provider_responses
        .iter()
        .map(ProviderSummary::from)
        .collect();

    let response_body = OpenRtbResponse {
        id: Some(auction_request.id.to_string()),
        seatbid: seatbids,
        ext: ResponseExt {
            orchestrator: OrchestratorExt {
                strategy: strategy_name.to_string(),
                providers: result.provider_responses.len(),
                total_bids: result.total_bids(),
                time_ms: result.total_time_ms,
                provider_details,
            },
        }
        .to_ext(),
        ..Default::default()
    };

    let body_bytes =
        serde_json::to_vec(&response_body).change_context(TrustedServerError::Auction {
            message: "Failed to serialize auction response".to_string(),
        })?;

    let mut response = Response::from_status(StatusCode::OK)
        .with_header(header::CONTENT_TYPE, "application/json")
        .with_body(body_bytes);

    // Signal consent status independently of whether EIDs were resolved.
    // A user may have granted consent but have no partner syncs yet;
    // downstream clients rely on this header to know consent was verified.
    if ec_allowed {
        response.set_header(HEADER_X_TS_EC_CONSENT, "ok");
    }

    // Attach EID response headers when consent-gated EIDs are available.
    // `Some(empty)` means "we looked and found no synced partners" — the
    // header is still set (with an encoded empty array) so clients can
    // distinguish this from `None` (EIDs not checked / consent denied).
    if let Some(ref eids) = auction_request.user.eids {
        let (encoded, truncated) = encode_eids_header(eids)?;
        response.set_header(HEADER_X_TS_EIDS, encoded);
        if truncated {
            response.set_header(HEADER_X_TS_EIDS_TRUNCATED, "true");
        }
    }

    Ok(response)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::auction::orchestrator::OrchestrationResult;
    use crate::auction::types::{AdFormat, AdSlot, MediaType};
    use crate::constants::{HEADER_X_TS_EC_CONSENT, HEADER_X_TS_EIDS, HEADER_X_TS_EIDS_TRUNCATED};
    use crate::openrtb::{Eid, Uid};

    fn make_minimal_auction_request() -> AuctionRequest {
        AuctionRequest {
            id: "test-auction".to_owned(),
            slots: vec![AdSlot {
                id: "slot-1".to_owned(),
                formats: vec![AdFormat {
                    media_type: MediaType::Banner,
                    width: 300,
                    height: 250,
                }],
                floor_price: None,
                targeting: HashMap::new(),
                bidders: HashMap::new(),
            }],
            publisher: PublisherInfo {
                domain: "test.com".to_owned(),
                page_url: None,
            },
            user: UserInfo {
                id: Some("test-ec-id".to_owned()),
                consent: None,
                eids: None,
            },
            device: None,
            site: None,
            context: HashMap::new(),
        }
    }

    fn make_empty_result() -> OrchestrationResult {
        OrchestrationResult {
            winning_bids: HashMap::new(),
            provider_responses: Vec::new(),
            mediator_response: None,
            total_time_ms: 10,
            metadata: HashMap::new(),
        }
    }

    fn make_settings() -> Settings {
        crate::test_support::tests::create_test_settings()
    }

    #[test]
    fn response_includes_eid_headers_when_eids_present() {
        let mut request = make_minimal_auction_request();
        request.user.eids = Some(vec![Eid {
            source: "ssp.com".to_owned(),
            uids: vec![Uid {
                id: "uid-1".to_owned(),
                atype: Some(3),
                ext: None,
            }],
        }]);

        let settings = make_settings();
        let result = make_empty_result();

        let response = convert_to_openrtb_response(&result, &settings, &request, true)
            .expect("should build response");

        assert!(
            response.get_header(HEADER_X_TS_EIDS).is_some(),
            "should include x-ts-eids header when EIDs are present"
        );
        assert_eq!(
            response
                .get_header(HEADER_X_TS_EC_CONSENT)
                .and_then(|v| v.to_str().ok()),
            Some("ok"),
            "should include x-ts-ec-consent: ok when ec_allowed is true"
        );
        assert!(
            response.get_header(HEADER_X_TS_EIDS_TRUNCATED).is_none(),
            "should not include truncated header for small payload"
        );
    }

    #[test]
    fn response_sets_consent_header_even_without_eids() {
        let request = make_minimal_auction_request();
        let settings = make_settings();
        let result = make_empty_result();

        let response = convert_to_openrtb_response(&result, &settings, &request, true)
            .expect("should build response");

        assert_eq!(
            response
                .get_header(HEADER_X_TS_EC_CONSENT)
                .and_then(|v| v.to_str().ok()),
            Some("ok"),
            "should set x-ts-ec-consent: ok based on consent, not EID presence"
        );
        assert!(
            response.get_header(HEADER_X_TS_EIDS).is_none(),
            "should omit x-ts-eids when no EIDs available"
        );
    }

    #[test]
    fn response_omits_consent_header_when_not_allowed() {
        let request = make_minimal_auction_request();
        let settings = make_settings();
        let result = make_empty_result();

        let response = convert_to_openrtb_response(&result, &settings, &request, false)
            .expect("should build response");

        assert!(
            response.get_header(HEADER_X_TS_EC_CONSENT).is_none(),
            "should omit x-ts-ec-consent when ec_allowed is false"
        );
        assert!(
            response.get_header(HEADER_X_TS_EIDS).is_none(),
            "should omit x-ts-eids when no EIDs available"
        );
        assert!(
            response.get_header("x-ts-ec").is_none(),
            "should not emit x-ts-ec when a valid EC is present"
        );
    }

    #[test]
    fn response_omits_ec_header_when_ec_id_is_none() {
        let mut request = make_minimal_auction_request();
        request.user.id = None;

        let settings = make_settings();
        let result = make_empty_result();

        let response = convert_to_openrtb_response(&result, &settings, &request, false)
            .expect("should build response");

        assert!(
            response.get_header("x-ts-ec").is_none(),
            "should omit x-ts-ec when no EC ID is available"
        );
    }
}

#[cfg(test)]
mod convert_tests {
    use super::*;
    use crate::consent::ConsentContext;
    use crate::test_support::tests::crate_test_settings_str;
    use fastly::http::Method;
    use fastly::Request;

    fn make_settings() -> Settings {
        Settings::from_toml(&crate_test_settings_str()).expect("should parse test settings")
    }

    fn make_req() -> Request {
        Request::new(Method::POST, "https://test-publisher.com/auction")
    }

    fn call_convert(body: &AdRequest) -> AuctionRequest {
        let settings = make_settings();
        let req = make_req();
        convert_tsjs_to_auction_request(
            body,
            &settings,
            &req,
            ConsentContext::default(),
            Some("test-ec-id"),
        )
        .expect("should convert without error")
    }

    #[test]
    fn no_bids_produces_empty_bidders_map() {
        // An ad unit with no `bids` array must produce an empty bidders map.
        // An empty bidders map triggers the PBS stored-request fallback:
        // the PBS provider sets imp.ext.prebid.storedrequest = { id: "<code>" }.
        let body = AdRequest {
            ad_units: vec![AdUnit {
                code: "atf_sidebar_ad".to_string(),
                media_types: Some(MediaTypes {
                    banner: Some(BannerUnit {
                        sizes: vec![vec![300, 250]],
                    }),
                }),
                bids: None,
            }],
            config: None,
            eids: None,
        };

        let auction_request = call_convert(&body);

        assert_eq!(auction_request.slots.len(), 1, "should have one slot");
        let slot = &auction_request.slots[0];
        assert_eq!(slot.id, "atf_sidebar_ad", "slot id should match unit code");
        assert!(
            slot.bidders.is_empty(),
            "absent bids array should yield empty bidders map (PBS stored-request path)"
        );
    }

    #[test]
    fn inline_bids_populate_bidders_map() {
        // When bids are supplied, each bidder+params pair should appear in the
        // slot's bidders map so PBS receives inline params.
        let body = AdRequest {
            ad_units: vec![AdUnit {
                code: "homepage_header_ad".to_string(),
                media_types: Some(MediaTypes {
                    banner: Some(BannerUnit {
                        sizes: vec![vec![970, 90]],
                    }),
                }),
                bids: Some(vec![BidConfig {
                    bidder: "kargo".to_string(),
                    params: serde_json::json!({ "placementId": "client_123" }),
                }]),
            }],
            config: None,
            eids: None,
        };

        let auction_request = call_convert(&body);

        let slot = &auction_request.slots[0];
        assert!(
            slot.bidders.contains_key("kargo"),
            "kargo bidder should be present in slot bidders map"
        );
        assert_eq!(
            slot.bidders["kargo"]["placementId"], "client_123",
            "bidder params should be forwarded verbatim"
        );
    }

    #[test]
    fn config_allowed_key_passes_through() {
        // Keys in auction.allowed_context_keys must reach the auction context.
        // The test settings do not set allowed_context_keys so the default
        // (empty) applies — verify a key is NOT present rather than IS.
        // To test the allow-list, inject a key via a custom settings string.
        let settings_str = format!(
            "{}\n[auction]\nallowed_context_keys = [\"permutive_segments\"]\n",
            crate_test_settings_str()
        );
        let settings = Settings::from_toml(&settings_str).expect("should parse");
        let req = make_req();

        let body = AdRequest {
            ad_units: vec![],
            config: Some(serde_json::json!({
                "permutive_segments": ["seg1", "seg2"],
                "disallowed_key": "should be dropped",
            })),
            eids: None,
        };

        let auction_request = convert_tsjs_to_auction_request(
            &body,
            &settings,
            &req,
            ConsentContext::default(),
            Some("test-ec-id"),
        )
        .expect("should convert");

        assert!(
            auction_request.context.contains_key("permutive_segments"),
            "allowed key should be in auction context"
        );
        assert!(
            !auction_request.context.contains_key("disallowed_key"),
            "unlisted key should be dropped"
        );
    }

    #[test]
    fn invalid_banner_size_returns_error() {
        // Banner sizes must be [width, height] pairs; a 3-element size is invalid.
        let body = AdRequest {
            ad_units: vec![AdUnit {
                code: "bad_slot".to_string(),
                media_types: Some(MediaTypes {
                    banner: Some(BannerUnit {
                        sizes: vec![vec![300, 250, 99]], // invalid — 3 elements
                    }),
                }),
                bids: None,
            }],
            config: None,
            eids: None,
        };

        let settings = make_settings();
        let req = make_req();
        let result = convert_tsjs_to_auction_request(
            &body,
            &settings,
            &req,
            ConsentContext::default(),
            Some("test-ec-id"),
        );

        assert!(
            result.is_err(),
            "3-element banner size should return an error"
        );
    }
}
