[package]
name = "trusted-server-fastly"
version = "0.1.0"
edition = "2021"

[dependencies]
fastly = "0.11.2"
futures = "0.3"
http = "1.3.1"
log = "0.4.20"
log-fastly = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.91"   
trusted-server-common = { path = "../common" }
