// @generated by openrtb-codegen from proto/openrtb.proto
// Do not edit manually — run `./crates/openrtb/generate.sh` to regenerate.
// source: proto/openrtb.proto

// This file is @generated by prost-build.
/// OpenRTB 2.0: The top-level bid request object.
#[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct BidRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: ::core::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub imp: ::std::vec::Vec<bid_request::Imp>,
    /// Distribution channel — flattened from oneof for JSON compat.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub site: ::core::option::Option<bid_request::Site>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub app: ::core::option::Option<bid_request::App>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dooh: ::core::option::Option<bid_request::Dooh>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device: ::core::option::Option<bid_request::Device>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user: ::core::option::Option<bid_request::User>,
    #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
    pub test: ::core::option::Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub at: ::core::option::Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tmax: ::core::option::Option<i32>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub wseat: ::std::vec::Vec<::std::string::String>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub bseat: ::std::vec::Vec<::std::string::String>,
    #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
    pub allimps: ::core::option::Option<bool>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub cur: ::std::vec::Vec<::std::string::String>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub wlang: ::std::vec::Vec<::std::string::String>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub wlangb: ::std::vec::Vec<::std::string::String>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub acat: ::std::vec::Vec<::std::string::String>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub bcat: ::std::vec::Vec<::std::string::String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cattax: ::core::option::Option<i32>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub badv: ::std::vec::Vec<::std::string::String>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub bapp: ::std::vec::Vec<::std::string::String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: ::core::option::Option<bid_request::Source>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub regs: ::core::option::Option<bid_request::Regs>,
    /// Placeholder for exchange-specific extensions to OpenRTB.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ext: ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
}
/// Nested message and enum types in `BidRequest`.
pub mod bid_request {
    /// Source object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Source {
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub fd: ::core::option::Option<bool>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub tid: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub pchain: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub schain: ::core::option::Option<SupplyChain>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// SupplyChain object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct SupplyChain {
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub complete: ::core::option::Option<bool>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub nodes: ::std::vec::Vec<SupplyChainNode>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ver: ::core::option::Option<::std::string::String>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// SupplyChainNode object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct SupplyChainNode {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub asi: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub sid: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub rid: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub name: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub domain: ::core::option::Option<::std::string::String>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub hp: ::core::option::Option<bool>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Imp object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Imp {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub id: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub metric: ::std::vec::Vec<Metric>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub banner: ::core::option::Option<Banner>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub video: ::core::option::Option<Video>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub audio: ::core::option::Option<Audio>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub native: ::core::option::Option<Native>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub pmp: ::core::option::Option<Pmp>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub displaymanager: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub displaymanagerver: ::core::option::Option<::std::string::String>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub instl: ::core::option::Option<bool>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub tagid: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub bidfloor: ::core::option::Option<f64>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub bidfloorcur: ::core::option::Option<::std::string::String>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub clickbrowser: ::core::option::Option<bool>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub secure: ::core::option::Option<bool>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub iframebuster: ::std::vec::Vec<::std::string::String>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub rwdd: ::core::option::Option<bool>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ssai: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub exp: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub qty: ::core::option::Option<Qty>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub dt: ::core::option::Option<f64>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub refresh: ::core::option::Option<Refresh>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Metric object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Metric {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub r#type: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub value: ::core::option::Option<f64>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub vendor: ::core::option::Option<::std::string::String>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Banner object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Banner {
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub format: ::std::vec::Vec<Format>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub w: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub h: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub btype: ::std::vec::Vec<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub battr: ::std::vec::Vec<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub pos: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub mimes: ::std::vec::Vec<::std::string::String>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub topframe: ::core::option::Option<bool>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub expdir: ::std::vec::Vec<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub api: ::std::vec::Vec<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub id: ::core::option::Option<::std::string::String>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub vcm: ::core::option::Option<bool>,
        #[deprecated]
        #[serde(skip_serializing_if = "Option::is_none")]
        pub wmax: ::core::option::Option<i32>,
        #[deprecated]
        #[serde(skip_serializing_if = "Option::is_none")]
        pub hmax: ::core::option::Option<i32>,
        #[deprecated]
        #[serde(skip_serializing_if = "Option::is_none")]
        pub wmin: ::core::option::Option<i32>,
        #[deprecated]
        #[serde(skip_serializing_if = "Option::is_none")]
        pub hmin: ::core::option::Option<i32>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Format object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Format {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub w: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub h: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub wratio: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub hratio: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub wmin: ::core::option::Option<i32>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Video object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Video {
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub mimes: ::std::vec::Vec<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub minduration: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub maxduration: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub startdelay: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub maxseq: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub poddur: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub protocols: ::std::vec::Vec<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub w: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub h: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub podid: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub podseq: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub rqddurs: ::std::vec::Vec<i32>,
        #[deprecated]
        #[serde(skip_serializing_if = "Option::is_none")]
        pub placement: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub plcmt: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub linearity: ::core::option::Option<i32>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub skip: ::core::option::Option<bool>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub skipmin: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub skipafter: ::core::option::Option<i32>,
        #[deprecated]
        #[serde(skip_serializing_if = "Option::is_none")]
        pub sequence: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub slotinpod: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub mincpmpersec: ::core::option::Option<f64>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub battr: ::std::vec::Vec<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub maxextended: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub minbitrate: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub maxbitrate: ::core::option::Option<i32>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub boxingallowed: ::core::option::Option<bool>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub playbackmethod: ::std::vec::Vec<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub playbackend: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub delivery: ::std::vec::Vec<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub pos: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub companionad: ::std::vec::Vec<Banner>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub api: ::std::vec::Vec<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub companiontype: ::std::vec::Vec<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub poddedupe: ::std::vec::Vec<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub durfloors: ::std::vec::Vec<DurFloors>,
        #[deprecated]
        #[serde(skip_serializing_if = "Option::is_none")]
        pub protocol: ::core::option::Option<i32>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Audio object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Audio {
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub mimes: ::std::vec::Vec<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub minduration: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub maxduration: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub poddur: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub protocols: ::std::vec::Vec<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub startdelay: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub rqddurs: ::std::vec::Vec<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub podid: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub podseq: ::core::option::Option<i32>,
        #[deprecated]
        #[serde(skip_serializing_if = "Option::is_none")]
        pub sequence: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub slotinpod: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub mincpmpersec: ::core::option::Option<f64>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub battr: ::std::vec::Vec<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub maxextended: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub minbitrate: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub maxbitrate: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub delivery: ::std::vec::Vec<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub companionad: ::std::vec::Vec<Banner>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub api: ::std::vec::Vec<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub companiontype: ::std::vec::Vec<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub maxseq: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub feed: ::core::option::Option<i32>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub stitched: ::core::option::Option<bool>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub nvol: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub durfloors: ::std::vec::Vec<DurFloors>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Native object.
    /// Flattened from oneof request_oneof for JSON compat.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Native {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub request: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub request_native: ::core::option::Option<super::NativeRequest>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ver: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub api: ::std::vec::Vec<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub battr: ::std::vec::Vec<i32>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Qty object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Qty {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub multiplier: ::core::option::Option<f64>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub sourcetype: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub vendor: ::core::option::Option<::std::string::String>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Refresh object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Refresh {
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub refsettings: ::std::vec::Vec<RefSettings>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub count: ::core::option::Option<i32>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// RefSettings object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct RefSettings {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub reftype: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub minint: ::core::option::Option<i32>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Pmp object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Pmp {
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub private_auction: ::core::option::Option<bool>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub deals: ::std::vec::Vec<Deal>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Deal object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Deal {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub id: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub bidfloor: ::core::option::Option<f64>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub bidfloorcur: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub at: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub wseat: ::std::vec::Vec<::std::string::String>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub wadomain: ::std::vec::Vec<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub guar: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub mincpmpersec: ::core::option::Option<f64>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub durfloors: ::std::vec::Vec<DurFloors>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Site object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Site {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub id: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub name: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub domain: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub cattax: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub cat: ::std::vec::Vec<::std::string::String>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub sectioncat: ::std::vec::Vec<::std::string::String>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub pagecat: ::std::vec::Vec<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub page: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub r#ref: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub search: ::core::option::Option<::std::string::String>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub mobile: ::core::option::Option<bool>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub privacypolicy: ::core::option::Option<bool>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub publisher: ::core::option::Option<Publisher>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub content: ::core::option::Option<Content>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub keywords: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub kwarray: ::std::vec::Vec<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub inventorypartnerdomain: ::core::option::Option<::std::string::String>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// App object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct App {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub id: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub name: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub bundle: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub domain: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub storeurl: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub cattax: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub cat: ::std::vec::Vec<::std::string::String>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub sectioncat: ::std::vec::Vec<::std::string::String>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub pagecat: ::std::vec::Vec<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ver: ::core::option::Option<::std::string::String>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub privacypolicy: ::core::option::Option<bool>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub paid: ::core::option::Option<bool>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub publisher: ::core::option::Option<Publisher>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub content: ::core::option::Option<Content>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub keywords: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub kwarray: ::std::vec::Vec<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub inventorypartnerdomain: ::core::option::Option<::std::string::String>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Dooh object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Dooh {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub id: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub name: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub venuetype: ::std::vec::Vec<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub venuetypetax: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub publisher: ::core::option::Option<Publisher>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub domain: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub keywords: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub content: ::core::option::Option<Content>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Publisher object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Publisher {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub id: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub name: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub cattax: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub cat: ::std::vec::Vec<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub domain: ::core::option::Option<::std::string::String>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Content object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Content {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub id: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub episode: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub title: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub series: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub season: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub artist: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub genre: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub gtax: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub genres: ::std::vec::Vec<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub album: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub isrc: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub producer: ::core::option::Option<Producer>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub url: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub cattax: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub cat: ::std::vec::Vec<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub prodq: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub context: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub contentrating: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub userrating: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub qagmediarating: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub keywords: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub kwarray: ::std::vec::Vec<::std::string::String>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub livestream: ::core::option::Option<bool>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub sourcerelationship: ::core::option::Option<bool>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub len: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub language: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub langb: ::core::option::Option<::std::string::String>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub embeddable: ::core::option::Option<bool>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub data: ::std::vec::Vec<Data>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub network: ::core::option::Option<Network>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub channel: ::core::option::Option<Channel>,
        #[deprecated]
        #[serde(skip_serializing_if = "Option::is_none")]
        pub videoquality: ::core::option::Option<i32>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Producer object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Producer {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub id: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub name: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub cattax: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub cat: ::std::vec::Vec<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub domain: ::core::option::Option<::std::string::String>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Network object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Network {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub id: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub name: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub domain: ::core::option::Option<::std::string::String>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Channel object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Channel {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub id: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub name: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub domain: ::core::option::Option<::std::string::String>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Device object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Device {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub geo: ::core::option::Option<Geo>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub dnt: ::core::option::Option<bool>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub lmt: ::core::option::Option<bool>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ua: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub sua: ::core::option::Option<UserAgent>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ip: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ipv6: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub devicetype: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub make: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub model: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub os: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub osv: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub hwv: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub w: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub h: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ppi: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub pxratio: ::core::option::Option<f64>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub js: ::core::option::Option<bool>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub geofetch: ::core::option::Option<bool>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub flashver: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub language: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub langb: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub carrier: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub mccmnc: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub connectiontype: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ifa: ::core::option::Option<::std::string::String>,
        #[deprecated]
        #[serde(skip_serializing_if = "Option::is_none")]
        pub didsha1: ::core::option::Option<::std::string::String>,
        #[deprecated]
        #[serde(skip_serializing_if = "Option::is_none")]
        pub didmd5: ::core::option::Option<::std::string::String>,
        #[deprecated]
        #[serde(skip_serializing_if = "Option::is_none")]
        pub dpidsha1: ::core::option::Option<::std::string::String>,
        #[deprecated]
        #[serde(skip_serializing_if = "Option::is_none")]
        pub dpidmd5: ::core::option::Option<::std::string::String>,
        #[deprecated]
        #[serde(skip_serializing_if = "Option::is_none")]
        pub macsha1: ::core::option::Option<::std::string::String>,
        #[deprecated]
        #[serde(skip_serializing_if = "Option::is_none")]
        pub macmd5: ::core::option::Option<::std::string::String>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Geo object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Geo {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub lat: ::core::option::Option<f64>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub lon: ::core::option::Option<f64>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub r#type: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub accuracy: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub lastfix: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ipservice: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub country: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub region: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub regionfips104: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub metro: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub city: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub zip: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub utcoffset: ::core::option::Option<i32>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// UserAgent object (Structured UA / Client Hints).
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct UserAgent {
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub browsers: ::std::vec::Vec<BrandVersion>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub platform: ::core::option::Option<BrandVersion>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub mobile: ::core::option::Option<bool>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub architecture: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub bitness: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub model: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub source: ::core::option::Option<i32>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// BrandVersion object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct BrandVersion {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub brand: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub version: ::std::vec::Vec<::std::string::String>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// User object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct User {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub id: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub buyeruid: ::core::option::Option<::std::string::String>,
        #[deprecated]
        #[serde(skip_serializing_if = "Option::is_none")]
        pub yob: ::core::option::Option<i32>,
        #[deprecated]
        #[serde(skip_serializing_if = "Option::is_none")]
        pub gender: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub keywords: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub kwarray: ::std::vec::Vec<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub customdata: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub geo: ::core::option::Option<Geo>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub data: ::std::vec::Vec<Data>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub consent: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub eids: ::std::vec::Vec<Eid>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// EID (Extended Identifier) object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Eid {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub inserter: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub source: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub matcher: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub mm: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub uids: ::std::vec::Vec<eid::Uid>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Nested message and enum types in `EID`.
    pub mod eid {
        /// UID object.
        #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
        #[serde(default)]
        pub struct Uid {
            #[serde(skip_serializing_if = "Option::is_none")]
            pub id: ::core::option::Option<::std::string::String>,
            #[serde(skip_serializing_if = "Option::is_none")]
            pub atype: ::core::option::Option<i32>,
            /// Placeholder for exchange-specific extensions to OpenRTB.
            #[serde(skip_serializing_if = "Option::is_none")]
            pub ext: ::core::option::Option<
                ::serde_json::Map<::std::string::String, ::serde_json::Value>,
            >,
        }
    }
    /// Data object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Data {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub id: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub name: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub segment: ::std::vec::Vec<Segment>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Segment object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Segment {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub id: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub name: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub value: ::core::option::Option<::std::string::String>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Regs object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Regs {
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub coppa: ::core::option::Option<bool>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub gdpr: ::core::option::Option<bool>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub us_privacy: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub gpp: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub gpp_sid: ::std::vec::Vec<i32>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// DurFloors object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct DurFloors {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub mindur: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub maxdur: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub bidfloor: ::core::option::Option<f64>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
}
/// BidResponse — top-level response object.
#[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct BidResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: ::core::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub seatbid: ::std::vec::Vec<bid_response::SeatBid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bidid: ::core::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cur: ::core::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub customdata: ::core::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nbr: ::core::option::Option<i32>,
    /// Placeholder for exchange-specific extensions to OpenRTB.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ext: ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
}
/// Nested message and enum types in `BidResponse`.
pub mod bid_response {
    /// SeatBid object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct SeatBid {
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub bid: ::std::vec::Vec<Bid>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub seat: ::core::option::Option<::std::string::String>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub group: ::core::option::Option<bool>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Bid object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Bid {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub id: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub impid: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub price: ::core::option::Option<f64>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub nurl: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub burl: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub lurl: ::core::option::Option<::std::string::String>,
        /// Flattened from oneof adm_oneof for JSON compat.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub adm: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub adm_native: ::core::option::Option<super::NativeResponse>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub adid: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub adomain: ::std::vec::Vec<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub bundle: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub iurl: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub cid: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub crid: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub tactic: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub cattax: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub cat: ::std::vec::Vec<::std::string::String>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub attr: ::std::vec::Vec<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub apis: ::std::vec::Vec<i32>,
        #[deprecated]
        #[serde(skip_serializing_if = "Option::is_none")]
        pub api: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub protocol: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub qagmediarating: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub language: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub langb: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub dealid: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub w: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub h: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub wratio: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub hratio: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub exp: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub dur: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub mtype: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub slotinpod: ::core::option::Option<i32>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
}
/// Transparency object (shared by request and response DSA).
#[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct Transparency {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: ::core::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub dsaparams: ::std::vec::Vec<i32>,
    /// Placeholder for exchange-specific extensions to OpenRTB.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ext: ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
}
/// NativeRequest object.
#[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct NativeRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ver: ::core::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub layout: ::core::option::Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub adunit: ::core::option::Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context: ::core::option::Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contextsubtype: ::core::option::Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plcmttype: ::core::option::Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub plcmtcnt: ::core::option::Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub seq: ::core::option::Option<i32>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub assets: ::std::vec::Vec<native_request::Asset>,
    #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
    pub aurlsupport: ::core::option::Option<bool>,
    #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
    pub durlsupport: ::core::option::Option<bool>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub eventtrackers: ::std::vec::Vec<native_request::EventTrackers>,
    #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
    pub privacy: ::core::option::Option<bool>,
}
/// Nested message and enum types in `NativeRequest`.
pub mod native_request {
    /// Asset object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Asset {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub id: ::core::option::Option<i32>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub required: ::core::option::Option<bool>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub title: ::core::option::Option<Title>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub img: ::core::option::Option<Image>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub video: ::core::option::Option<super::bid_request::Video>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub data: ::core::option::Option<Data>,
    }
    /// Title object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Title {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub len: ::core::option::Option<i32>,
    }
    /// Image object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Image {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub r#type: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub w: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub h: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub wmin: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub hmin: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub mimes: ::std::vec::Vec<::std::string::String>,
    }
    /// Data object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Data {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub r#type: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub len: ::core::option::Option<i32>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// EventTrackers object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct EventTrackers {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub event: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub methods: ::std::vec::Vec<i32>,
    }
}
/// NativeResponse object.
#[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
#[serde(default)]
pub struct NativeResponse {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ver: ::core::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub assets: ::std::vec::Vec<native_response::Asset>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub assetsurl: ::core::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dcourl: ::core::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub link: ::core::option::Option<native_response::Link>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub imptrackers: ::std::vec::Vec<::std::string::String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub jstracker: ::core::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub eventtrackers: ::std::vec::Vec<native_response::EventTracker>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub privacy: ::core::option::Option<::std::string::String>,
}
/// Nested message and enum types in `NativeResponse`.
pub mod native_response {
    /// Link object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Link {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub url: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Vec::is_empty", default)]
        pub clicktrackers: ::std::vec::Vec<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub fallback: ::core::option::Option<::std::string::String>,
    }
    /// Asset object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Asset {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub id: ::core::option::Option<i32>,
        #[serde(with = "crate::bool_as_int", skip_serializing_if = "Option::is_none")]
        pub required: ::core::option::Option<bool>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub title: ::core::option::Option<Title>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub img: ::core::option::Option<Image>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub video: ::core::option::Option<Video>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub data: ::core::option::Option<Data>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub link: ::core::option::Option<Link>,
    }
    /// Title object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Title {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub text: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub len: ::core::option::Option<i32>,
    }
    /// Image object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Image {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub r#type: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub url: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub w: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub h: ::core::option::Option<i32>,
    }
    /// Data object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Data {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub r#type: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub len: ::core::option::Option<i32>,
        #[deprecated]
        #[serde(skip_serializing_if = "Option::is_none")]
        pub label: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub value: ::core::option::Option<::std::string::String>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// Video object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct Video {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub vasttag: ::core::option::Option<::std::string::String>,
        /// Placeholder for exchange-specific extensions to OpenRTB.
        #[serde(skip_serializing_if = "Option::is_none")]
        pub ext:
            ::core::option::Option<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    }
    /// EventTracker object.
    #[derive(Clone, Debug, Default, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    #[serde(default)]
    pub struct EventTracker {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub event: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub method: ::core::option::Option<i32>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub url: ::core::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub customdata: ::core::option::Option<::std::string::String>,
    }
}
#[derive(
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
    Hash,
    PartialOrd,
    Ord,
    ::serde::Serialize,
    ::serde::Deserialize,
)]
#[repr(i32)]
pub enum BannerAdType {
    Unknown = 0,
    XhtmlTextAd = 1,
    XhtmlBannerAd = 2,
    JavascriptAd = 3,
    Iframe = 4,
}
impl BannerAdType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "BannerAdType_UNKNOWN",
            Self::XhtmlTextAd => "XHTML_TEXT_AD",
            Self::XhtmlBannerAd => "XHTML_BANNER_AD",
            Self::JavascriptAd => "JAVASCRIPT_AD",
            Self::Iframe => "IFRAME",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BannerAdType_UNKNOWN" => Some(Self::Unknown),
            "XHTML_TEXT_AD" => Some(Self::XhtmlTextAd),
            "XHTML_BANNER_AD" => Some(Self::XhtmlBannerAd),
            "JAVASCRIPT_AD" => Some(Self::JavascriptAd),
            "IFRAME" => Some(Self::Iframe),
            _ => None,
        }
    }
}
#[derive(
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
    Hash,
    PartialOrd,
    Ord,
    ::serde::Serialize,
    ::serde::Deserialize,
)]
#[repr(i32)]
pub enum LayoutId {
    Unknown = 0,
    ContentWall = 1,
    AppWall = 2,
    NewsFeed = 3,
    ChatList = 4,
    Carousel = 5,
    ContentStream = 6,
    Grid = 7,
}
impl LayoutId {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "LayoutId_UNKNOWN",
            Self::ContentWall => "CONTENT_WALL",
            Self::AppWall => "APP_WALL",
            Self::NewsFeed => "NEWS_FEED",
            Self::ChatList => "CHAT_LIST",
            Self::Carousel => "CAROUSEL",
            Self::ContentStream => "CONTENT_STREAM",
            Self::Grid => "GRID",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LayoutId_UNKNOWN" => Some(Self::Unknown),
            "CONTENT_WALL" => Some(Self::ContentWall),
            "APP_WALL" => Some(Self::AppWall),
            "NEWS_FEED" => Some(Self::NewsFeed),
            "CHAT_LIST" => Some(Self::ChatList),
            "CAROUSEL" => Some(Self::Carousel),
            "CONTENT_STREAM" => Some(Self::ContentStream),
            "GRID" => Some(Self::Grid),
            _ => None,
        }
    }
}
#[derive(
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
    Hash,
    PartialOrd,
    Ord,
    ::serde::Serialize,
    ::serde::Deserialize,
)]
#[repr(i32)]
pub enum AdUnitId {
    Unknown = 0,
    PaidSearchUnit = 1,
    RecommendationWidget = 2,
    PromotedListing = 3,
    IabInAdNative = 4,
    AdunitidCustom = 5,
}
impl AdUnitId {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "AdUnitId_UNKNOWN",
            Self::PaidSearchUnit => "PAID_SEARCH_UNIT",
            Self::RecommendationWidget => "RECOMMENDATION_WIDGET",
            Self::PromotedListing => "PROMOTED_LISTING",
            Self::IabInAdNative => "IAB_IN_AD_NATIVE",
            Self::AdunitidCustom => "ADUNITID_CUSTOM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AdUnitId_UNKNOWN" => Some(Self::Unknown),
            "PAID_SEARCH_UNIT" => Some(Self::PaidSearchUnit),
            "RECOMMENDATION_WIDGET" => Some(Self::RecommendationWidget),
            "PROMOTED_LISTING" => Some(Self::PromotedListing),
            "IAB_IN_AD_NATIVE" => Some(Self::IabInAdNative),
            "ADUNITID_CUSTOM" => Some(Self::AdunitidCustom),
            _ => None,
        }
    }
}
#[derive(
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
    Hash,
    PartialOrd,
    Ord,
    ::serde::Serialize,
    ::serde::Deserialize,
)]
#[repr(i32)]
pub enum ContextType {
    Unknown = 0,
    Content = 1,
    Social = 2,
    Product = 3,
}
impl ContextType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "ContextType_UNKNOWN",
            Self::Content => "CONTENT",
            Self::Social => "SOCIAL",
            Self::Product => "PRODUCT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ContextType_UNKNOWN" => Some(Self::Unknown),
            "CONTENT" => Some(Self::Content),
            "SOCIAL" => Some(Self::Social),
            "PRODUCT" => Some(Self::Product),
            _ => None,
        }
    }
}
