[app]
name = "trusted-server"
version = "0.1.0"
kind = "http"

[adapters.spin]

[stores.kv]
ids = ["trusted_server_kv"]
default = "trusted_server_kv"

[stores.config]
ids = ["trusted_server_config"]
default = "trusted_server_config"

[stores.secrets]
ids = ["trusted_server_secrets"]
default = "trusted_server_secrets"
