/**
 * Multi-entry Vite build script.
 *
 * Builds each integration as a separate IIFE file so the Rust server can
 * concatenate only the enabled modules at runtime.
 *
 * Output (in ../dist/):
 *   tsjs-core.js          — core API (always included)
 *   tsjs-<integration>.js — one per discovered integration
 *
 * Environment variables:
 *   TSJS_PREBID_ADAPTERS — Comma-separated list of Prebid.js bid adapter
 *     names to include in the bundle (e.g. "rubicon,appnexus,openx").
 *     Each name must have a corresponding {name}BidAdapter.js module in
 *     the prebid.js package. Default: "rubicon".
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'vite';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.resolve(__dirname, 'src');
const distDir = path.resolve(__dirname, '..', 'dist');
const integrationsDir = path.join(srcDir, 'integrations');

// ---------------------------------------------------------------------------
// Prebid adapter generation
// ---------------------------------------------------------------------------

const DEFAULT_PREBID_ADAPTERS = 'rubicon';
const ADAPTERS_FILE = path.join(
  integrationsDir,
  'prebid',
  '_adapters.generated.ts',
);

/**
 * Generate `_adapters.generated.ts` with import statements for each adapter
 * listed in the TSJS_PREBID_ADAPTERS environment variable.
 *
 * Invalid adapter names (those without a matching module in prebid.js) are
 * logged and skipped.
 */
function generatePrebidAdapters() {
  const raw = process.env.TSJS_PREBID_ADAPTERS || DEFAULT_PREBID_ADAPTERS;
  const names = raw
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);

  if (names.length === 0) {
    console.warn(
      '[build-all] TSJS_PREBID_ADAPTERS is empty, falling back to default:',
      DEFAULT_PREBID_ADAPTERS,
    );
    names.push(DEFAULT_PREBID_ADAPTERS);
  }

  const modulesDir = path.join(
    __dirname,
    'node_modules',
    'prebid.js',
    'modules',
  );

  // Validate each adapter and build import lines
  const imports = [];
  for (const name of names) {
    const moduleFile = `${name}BidAdapter.js`;
    const modulePath = path.join(modulesDir, moduleFile);
    if (!fs.existsSync(modulePath)) {
      console.error(
        `[build-all] WARNING: Prebid adapter "${name}" not found (expected ${moduleFile}), skipping`,
      );
      continue;
    }
    imports.push(`import 'prebid.js/modules/${moduleFile}';`);
  }

  if (imports.length === 0) {
    console.error(
      '[build-all] WARNING: No valid Prebid adapters found, bundle will have no client-side adapters',
    );
  }

  const content = [
    '// Auto-generated by build-all.mjs — manual edits will be overwritten at build time.',
    '//',
    '// Controls which Prebid.js bid adapters are included in the bundle.',
    '// Set the TSJS_PREBID_ADAPTERS environment variable to a comma-separated list',
    '// of adapter names (e.g. "rubicon,appnexus,openx") before building.',
    `// Default: "${DEFAULT_PREBID_ADAPTERS}"`,
    '',
    ...imports,
    '',
  ].join('\n');

  fs.writeFileSync(ADAPTERS_FILE, content);

  const adapterNames = names.filter((name) =>
    fs.existsSync(path.join(modulesDir, `${name}BidAdapter.js`)),
  );
  console.log('[build-all] Prebid adapters:', adapterNames);
}

generatePrebidAdapters();

// ---------------------------------------------------------------------------

// Clean dist directory
fs.rmSync(distDir, { recursive: true, force: true });
fs.mkdirSync(distDir, { recursive: true });

// Discover integration modules: directories in src/integrations/ with index.ts
const integrationModules = fs.existsSync(integrationsDir)
  ? fs
      .readdirSync(integrationsDir)
      .filter((name) => {
        const fullPath = path.join(integrationsDir, name);
        return (
          fs.statSync(fullPath).isDirectory() &&
          fs.existsSync(path.join(fullPath, 'index.ts'))
        );
      })
      .sort()
  : [];

console.log('[build-all] Discovered integrations:', integrationModules);

/** Build a single module as a self-contained IIFE. */
async function buildModule(name, entryPath) {
  const outFile = `tsjs-${name}.js`;
  console.log(`[build-all] Building ${outFile} from ${path.relative(__dirname, entryPath)}`);

  await build({
    configFile: false,
    root: __dirname,
    resolve: {
      alias: {
        // prebid.js doesn't expose src/adapterManager.js via its package
        // "exports" map, but we need it for client-side bidder validation.
        'prebid.js/src/adapterManager.js': path.resolve(
          __dirname,
          'node_modules/prebid.js/dist/src/src/adapterManager.js',
        ),
      },
    },
    build: {
      emptyOutDir: false,
      outDir: distDir,
      assetsDir: '.',
      sourcemap: false,
      minify: 'esbuild',
      rollupOptions: {
        input: entryPath,
        output: {
          format: 'iife',
          dir: distDir,
          entryFileNames: outFile,
          inlineDynamicImports: true,
          extend: false,
          // Use a unique IIFE name per module to avoid conflicts
          name: name === 'core' ? 'tsjs' : `tsjs_${name}`,
        },
      },
    },
    logLevel: 'warn',
  });

  console.log(`[build-all] Built ${outFile}`);
}

// Build core first (synchronously), then all integrations in parallel
await buildModule('core', path.join(srcDir, 'core', 'index.ts'));

await Promise.all(
  integrationModules.map((name) =>
    buildModule(name, path.join(integrationsDir, name, 'index.ts')),
  ),
);

// List all built files
const builtFiles = fs
  .readdirSync(distDir)
  .filter((f) => f.startsWith('tsjs-') && f.endsWith('.js'))
  .sort();

console.log('[build-all] Built files:', builtFiles);
console.log(`[build-all] Total: ${builtFiles.length} modules`);
