import fs from 'node:fs';
import path from 'node:path';

import { defineConfig } from 'vite';
import type { Plugin } from 'vite';

/**
 * Vite plugin that auto-discovers modules and generates conditional imports
 * based on TSJS_MODULES environment variable.
 */
function createModuleDiscoveryPlugin(): Plugin {
  return {
    name: 'tsjs-module-discovery',
    buildStart() {
      const srcDir = path.resolve(__dirname, 'src');

      // Read TSJS_MODULES env var: core,ext,creative,permutive
      const modulesEnv = process.env.TSJS_MODULES || '';
      const requestedModules = modulesEnv
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean);

      // Auto-discover all directories in src/ that contain index.ts
      const allDirs = fs
        .readdirSync(srcDir)
        .filter((name) => {
          const fullPath = path.join(srcDir, name);
          const stat = fs.statSync(fullPath);
          return stat.isDirectory();
        });

      // Find modules: directories with index.ts, excluding 'shared'
      const discoveredModules = allDirs.filter((folder) => {
        if (folder === 'shared') return false; // Skip utility folder
        return fs.existsSync(path.join(srcDir, folder, 'index.ts'));
      });

      // Filter by requested modules (if specified), otherwise include all
      const finalModules =
        requestedModules.length > 0
          ? discoveredModules.filter((folder) => requestedModules.includes(folder))
          : discoveredModules;

      // Always ensure 'core' is included if it exists
      if (discoveredModules.includes('core') && !finalModules.includes('core')) {
        finalModules.unshift('core');
      }

      // Generate import statements
      // Use namespace imports to capture all exports from each module
      const importLines: string[] = [];
      const exportEntries: string[] = [];

      for (const moduleName of finalModules) {
        importLines.push(`import * as ${moduleName} from './${moduleName}/index';`);
        exportEntries.push(`  ${moduleName},`);
      }

      // Write the generated file
      const output = `// Auto-generated by vite-plugin-tsjs-module-discovery
// DO NOT EDIT - This file is generated at build time based on TSJS_MODULES env var
${importLines.join('\n')}

export const modules = {
${exportEntries.join('\n')}
};

export type ModuleName = ${finalModules.map((m) => `'${m}'`).join(' | ')};
`;

      const generatedFilePath = path.join(srcDir, 'generated-modules.ts');
      fs.writeFileSync(generatedFilePath, output);

      console.log('[tsjs-module-discovery] Generated src/generated-modules.ts');
      console.log('[tsjs-module-discovery] Discovered modules:', discoveredModules);
      console.log('[tsjs-module-discovery] Included modules:', finalModules);
    },
  };
}

export default defineConfig(() => {
  const distDir = path.resolve(__dirname, '../dist');
  const buildTimestamp = new Date().toISOString();
  const banner = `// build: ${buildTimestamp}\n`;

  return {
    build: {
      emptyOutDir: false,
      outDir: distDir,
      assetsDir: '.',
      sourcemap: false,
      minify: 'esbuild',
      rollupOptions: {
        input: path.resolve(__dirname, 'src/index.ts'),
        output: {
          format: 'iife',
          dir: distDir,
          entryFileNames: 'tsjs-unified.js',
          inlineDynamicImports: true,
          extend: false,
          name: 'tsjs',
        },
      },
    },
    plugins: [createModuleDiscoveryPlugin()],
  };
});
