import fs from 'node:fs';
import path from 'node:path';

import { defineConfig } from 'vite';
import type { Plugin } from 'vite';

/**
 * Vite plugin that auto-discovers modules and generates conditional imports
 * based on TSJS_MODULES environment variable.
 */
function createModuleDiscoveryPlugin(): Plugin {
  return {
    name: 'tsjs-module-discovery',
    buildStart() {
      const srcDir = path.resolve(__dirname, 'src');
      const integrationsDir = path.join(srcDir, 'integrations');

      // Read TSJS_MODULES env var: creative,ext,testlight
      // - If not set or empty string: include all integrations (default behavior)
      // - If set to comma-separated list: include only those integrations
      const modulesEnv = process.env.TSJS_MODULES;
      const requestedModules = (modulesEnv || '')
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean);

      // Discover integration modules: directories in src/integrations/ with index.ts
      const integrationModules = fs.existsSync(integrationsDir)
        ? fs
            .readdirSync(integrationsDir)
            .filter((name) => {
              const fullPath = path.join(integrationsDir, name);
              const stat = fs.statSync(fullPath);
              return (
                stat.isDirectory() &&
                fs.existsSync(path.join(fullPath, 'index.ts'))
              );
            })
        : [];

      // Always include core first
      const finalModules = ['core'];

      // Add requested integrations based on TSJS_MODULES env var
      if (requestedModules.length === 0) {
        // TSJS_MODULES not set or empty: include all discovered integrations
        finalModules.push(...integrationModules);
      } else {
        // TSJS_MODULES set to list: include only requested integrations (excluding 'core' as it's always added)
        const requestedIntegrations = requestedModules.filter((m) => m !== 'core');
        finalModules.push(
          ...integrationModules.filter((m) => requestedIntegrations.includes(m))
        );
      }

      // Generate import statements
      // Use namespace imports to capture all exports from each module
      const importLines: string[] = [];
      const exportEntries: string[] = [];

      for (const moduleName of finalModules) {
        if (moduleName === 'core') {
          importLines.push(`import * as core from './core/index';`);
        } else {
          importLines.push(
            `import * as ${moduleName} from './integrations/${moduleName}/index';`
          );
        }
        exportEntries.push(`  ${moduleName},`);
      }

      // Write the generated file
      const output = `// Auto-generated by vite-plugin-tsjs-module-discovery
// DO NOT EDIT - This file is generated at build time based on TSJS_MODULES env var
${importLines.join('\n')}

export const modules = {
${exportEntries.join('\n')}
};

export type ModuleName = ${finalModules.map((m) => `'${m}'`).join(' | ')};
`;

      const generatedFilePath = path.join(srcDir, 'generated-modules.ts');
      fs.writeFileSync(generatedFilePath, output);

      console.log('[tsjs-module-discovery] Generated src/generated-modules.ts');
      console.log('[tsjs-module-discovery] Discovered integrations:', integrationModules);
      console.log('[tsjs-module-discovery] Included modules:', finalModules);
    },
  };
}

export default defineConfig(() => {
  const distDir = path.resolve(__dirname, '../dist');
  const buildTimestamp = new Date().toISOString();
  const banner = `// build: ${buildTimestamp}\n`;

  return {
    build: {
      emptyOutDir: false,
      outDir: distDir,
      assetsDir: '.',
      sourcemap: false,
      minify: 'esbuild',
      rollupOptions: {
        input: path.resolve(__dirname, 'src/index.ts'),
        output: {
          format: 'iife',
          dir: distDir,
          entryFileNames: 'tsjs-unified.js',
          inlineDynamicImports: true,
          extend: false,
          name: 'tsjs',
        },
      },
    },
    plugins: [createModuleDiscoveryPlugin()],
  };
});
