// Edge-injected GPT auction bootstrap.
//
// This is the minimal `window.tsjs.adInit` that runs on first page load
// before the TSJS bundle has had a chance to install its richer
// idempotent implementation. The bundle in
// crates/js/lib/src/integrations/gpt/index.ts overwrites `tsjs.adInit`
// once it loads.
//
// Contract with the bundle:
//   - Both implementations must set `window.tsjs.servicesEnabled = true`
//     after calling `enableSingleRequest()`/`enableServices()` so a
//     subsequent call becomes a no-op.
//   - `refresh()` is called only for the slots defined in this pass,
//     never the global slot list.
//
// Only installed if `window.tsjs.adInit` isn't already defined.
(function () {
  if (typeof window === "undefined") return;
  var ts = (window.tsjs = window.tsjs || {});
  if (ts.adInit) return;

  ts.adInit = function () {
    var slots = ts.adSlots || [];
    var bids = ts.bids || {};
    var divToSlotId = {};
    googletag.cmd.push(function () {
      // Slots TS defined itself — tracked for SPA destroy. Publisher-owned
      // slots are reused but never destroyed by TS on navigation.
      var newSlots = [];
      // All slots to refresh (TS-defined + publisher-owned reused).
      var slotsToRefresh = [];
      slots.forEach(function (slot) {
        // Resolve actual div ID: exact match first, then prefix query.
        // div_id in config may be a stable prefix (e.g. "ad-header-0-") when
        // the suffix is dynamically generated by the framework at render time.
        var el =
          document.getElementById(slot.div_id) ||
          document.querySelector(
            "[id^='" + slot.div_id + "']:not([id$='-container'])",
          );
        if (!el) return;
        var actualDivId = el.id;

        // Reuse publisher's existing GPT slot when present — avoids duplicate
        // slot definitions on the same div and lets TS inject bid targeting
        // onto the slot the publisher already configured in GAM.
        // If no publisher slot exists yet (async framework race), fall back to
        // defining TS's own slot so bid targeting still reaches GAM.
        var existingSlots = googletag.pubads().getSlots();
        var s =
          existingSlots.find(function (gs) {
            return gs.getSlotElementId() === actualDivId;
          }) || null;
        var tsOwned = false;
        if (!s) {
          // Use outer container div for TS's slot when publisher hasn't defined
          // theirs yet — keeps both slots on separate divs so publisher's
          // later defineSlot on the inner div doesn't conflict.
          var containerEl = document.getElementById(actualDivId + "-container");
          var slotDivId = containerEl ? containerEl.id : actualDivId;
          s = googletag.defineSlot(slot.gam_unit_path, slot.formats, slotDivId);
          if (!s) return;
          s.addService(googletag.pubads());
          tsOwned = true;
        }

        Object.entries(slot.targeting || {}).forEach(function (e) {
          s.setTargeting(e[0], e[1]);
        });
        var b = bids[slot.id] || {};
        ["hb_pb", "hb_bidder", "hb_adid"].forEach(function (k) {
          if (b[k]) s.setTargeting(k, b[k]);
        });
        // Keep in sync with TS_INITIAL_TARGETING_KEY in index.ts
        s.setTargeting("ts_initial", "1");
        divToSlotId[actualDivId] = slot.id;
        if (tsOwned) newSlots.push(s);
        slotsToRefresh.push(s);
      });
      ts.prevGptSlots = newSlots;
      ts.divToSlotId = divToSlotId;
      if (!ts.servicesEnabled) {
        googletag.pubads().enableSingleRequest();
        googletag.enableServices();
        ts.servicesEnabled = true;
        googletag
          .pubads()
          .addEventListener("slotRenderEnded", function (ev) {
            var divId = ev.slot.getSlotElementId();
            var slotId = (ts.divToSlotId || {})[divId];
            if (!slotId) return;
            var b = (ts.bids || {})[slotId] || {};
            var ourBidWon =
              !ev.isEmpty &&
              (b.hb_adid
                ? ev.slot.getTargeting("hb_adid")[0] === b.hb_adid
                : !!b.hb_bidder);
            if (ourBidWon) {
              if (b.nurl) navigator.sendBeacon(b.nurl);
              if (b.burl) navigator.sendBeacon(b.burl);
            }
          });
      }
      if (slotsToRefresh.length > 0) {
        googletag.pubads().refresh(slotsToRefresh);
      }
    });
  };
})();
