// Edge-injected GPT auction bootstrap.
//
// This is the minimal `window.tsjs.adInit` that runs on first page load
// before the TSJS bundle has had a chance to install its richer
// idempotent implementation. The bundle in
// crates/js/lib/src/integrations/gpt/index.ts overwrites `tsjs.adInit`
// once it loads.
//
// Contract with the bundle:
//   - Both implementations must set `window.tsjs.servicesEnabled = true`
//     after calling `enableSingleRequest()`/`enableServices()` so a
//     subsequent call becomes a no-op.
//   - `refresh()` is called only for the slots defined in this pass,
//     never the global slot list.
//
// Only installed if `window.tsjs.adInit` isn't already defined.
(function () {
  if (typeof window === "undefined") return;
  var ts = (window.tsjs = window.tsjs || {});
  if (ts.adInit) return;

  // Track whether the publisher disabled GPT initial load. GPT exposes no
  // getter for this, so wrap pubads().disableInitialLoad() to record it. With
  // initial load disabled, display() only registers a slot and the ad request
  // must come from a later refresh(); adInit() reads this to refresh its own
  // freshly defined slots so they are not left blank. Pushed onto the command
  // queue so it runs before the publisher's own disableInitialLoad() call.
  (window.googletag = window.googletag || { cmd: [] }).cmd.push(function () {
    var pubads = googletag.pubads && googletag.pubads();
    if (
      !pubads ||
      typeof pubads.disableInitialLoad !== "function" ||
      pubads.__tsInitialLoadHooked
    ) {
      return;
    }
    var original = pubads.disableInitialLoad.bind(pubads);
    pubads.disableInitialLoad = function () {
      ts.gptInitialLoadDisabled = true;
      return original();
    };
    pubads.__tsInitialLoadHooked = true;
  });

  ts.adInit = function () {
    var slots = ts.adSlots || [];
    var bids = ts.bids || {};
    var divToSlotId = {};

    googletag.cmd.push(function () {
      // Slots TS defined itself — tracked for SPA destroy. Publisher-owned
      // slots are reused but never destroyed by TS on navigation.
      var newSlots = [];
      // Publisher-owned slots TS reused — refreshed to pick up server-side
      // targeting. The publisher already display()ed these.
      var slotsToRefresh = [];
      // Element IDs of slots TS defined itself. GPT requires display() to
      // register/render a freshly-defined slot; refresh() alone no-ops for a
      // slot that was never displayed, so these are display()ed instead.
      var slotsToDisplay = [];
      slots.forEach(function (slot) {
        // Resolve actual div ID: exact match first, then safe prefix scan.
        // div_id in config may be a stable prefix (e.g. "ad-header-0-") when
        // the suffix is dynamically generated by the framework at render time.
        var el = document.getElementById(slot.div_id);
        if (!el) {
          var idElements = document.querySelectorAll("[id]");
          for (var i = 0; i < idElements.length; i++) {
            var candidate = idElements[i];
            if (
              candidate.id.startsWith(slot.div_id) &&
              !candidate.id.endsWith("-container")
            ) {
              el = candidate;
              break;
            }
          }
        }
        if (!el) return;
        var actualDivId = el.id;
        var b = bids[slot.id] || {};

        var existingSlots = googletag.pubads().getSlots();
        var s =
          existingSlots.find(function (gs) {
            return gs.getSlotElementId() === actualDivId;
          }) || null;
        var tsOwned = false;
        if (!s) {
          // Use outer container div for TS's slot when publisher hasn't defined
          // theirs yet — keeps both slots on separate divs so publisher's
          // later defineSlot on the inner div doesn't conflict.
          var containerEl = document.getElementById(actualDivId + "-container");
          var slotDivId = containerEl ? containerEl.id : actualDivId;
          s = googletag.defineSlot(slot.gam_unit_path, slot.formats, slotDivId);
          if (!s) return;
          s.addService(googletag.pubads());
          tsOwned = true;
        }

        Object.entries(slot.targeting || {}).forEach(function (e) {
          s.setTargeting(e[0], e[1]);
        });
        [
          "hb_pb",
          "hb_bidder",
          "hb_adid",
          "hb_cache_host",
          "hb_cache_path",
        ].forEach(function (k) {
          if (b[k]) s.setTargeting(k, b[k]);
        });
        // Keep in sync with TS_INITIAL_TARGETING_KEY in index.ts
        s.setTargeting("ts_initial", "1");
        // Map both the inner div and the GPT slot's element ID (the
        // "-container" div when TS defined the slot there) so slotRenderEnded
        // — which reports the GPT slot element ID — can find the slot for
        // nurl/burl beacon firing.
        divToSlotId[actualDivId] = slot.id;
        var slotElementId = s.getSlotElementId();
        if (slotElementId && slotElementId !== actualDivId) {
          divToSlotId[slotElementId] = slot.id;
        }
        if (tsOwned) {
          newSlots.push(s);
          var displayId = s.getSlotElementId() || actualDivId;
          slotsToDisplay.push(displayId);
        } else {
          slotsToRefresh.push(s);
        }
      });
      ts.prevGptSlots = newSlots;
      ts.divToSlotId = divToSlotId;
      if (!ts.servicesEnabled) {
        googletag.pubads().enableSingleRequest();
        googletag.enableServices();
        ts.servicesEnabled = true;
      }
      // Register and render TS-defined slots. GPT requires display() for a
      // freshly-defined slot; without it the slot no-ops and misses its
      // impression. Runs after enableServices(); on SPA navigation services are
      // already enabled, so this runs unconditionally for new slots.
      slotsToDisplay.forEach(function (divId) {
        googletag.display(divId);
      });
      // Reused publisher-owned slots always need a refresh to pick up the
      // server-side targeting. TS-defined slots are fetched by display() above
      // unless the publisher disabled initial load, in which case display() only
      // registers them and refresh() must request the ad — otherwise they render
      // blank. Only add them in that case to avoid double-requesting.
      var slotsNeedingRefresh = ts.gptInitialLoadDisabled
        ? slotsToRefresh.concat(newSlots)
        : slotsToRefresh;
      if (slotsNeedingRefresh.length > 0) {
        // One-shot bypass: this internal refresh delivers the just-applied
        // server-side targeting to GAM. If slim-Prebid has already wrapped
        // refresh(), it must pass this call straight through — not clear the
        // targeting and run a duplicate client-side auction. Mirrors the
        // bundle's adInit() in crates/js/lib/src/integrations/gpt/index.ts.
        ts.adInitRefreshInProgress = true;
        try {
          googletag.pubads().refresh(slotsNeedingRefresh);
        } finally {
          ts.adInitRefreshInProgress = false;
        }
      }
    });
  };
})();
