use core::str;
use error_stack::{Report, ResultExt};
use validator::Validate;

use crate::error::TrustedServerError;
use crate::settings::Settings;

pub use crate::auction_config_types::AuctionConfig;

const SETTINGS_DATA: &[u8] = include_bytes!("../../../target/trusted-server-out.toml");

/// Creates a new [`Settings`] instance from the embedded configuration file.
///
/// Loads the pre-built TOML that was generated by `build.rs` (base config
/// merged with any `TRUSTED_SERVER__` environment variable overrides at
/// build time). Environment variables are **not** read at runtime.
///
/// # Errors
///
/// - [`TrustedServerError::InvalidUtf8`] if the embedded TOML file contains invalid UTF-8
/// - [`TrustedServerError::Configuration`] if the configuration is invalid or missing required fields
pub fn get_settings() -> Result<Settings, Report<TrustedServerError>> {
    let toml_bytes = SETTINGS_DATA;
    let toml_str = str::from_utf8(toml_bytes).change_context(TrustedServerError::InvalidUtf8 {
        message: "embedded trusted-server.toml file".to_string(),
    })?;

    let settings = Settings::from_toml(toml_str)?;

    // Validate the settings
    settings
        .validate()
        .change_context(TrustedServerError::Configuration {
            message: "Failed to validate configuration".to_string(),
        })?;

    if !settings.proxy.certificate_check {
        log::warn!(
            "INSECURE: proxy.certificate_check is disabled — TLS certificates will NOT be verified"
        );
    }

    if settings.synthetic.secret_key.expose() == "trusted-server" {
        log::warn!(
            "INSECURE: synthetic.secret_key is set to the default placeholder — \
             HMAC-SHA256 signatures can be forged. \
             Override via TRUSTED_SERVER__SYNTHETIC__SECRET_KEY at build time"
        );
    }

    if settings.publisher.proxy_secret.expose() == "change-me-proxy-secret" {
        log::warn!(
            "INSECURE: publisher.proxy_secret is set to the default placeholder — \
             XChaCha20-Poly1305 encrypted URLs can be decrypted by anyone. \
             Override via TRUSTED_SERVER__PUBLISHER__PROXY_SECRET at build time"
        );
    }

    Ok(settings)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn get_settings_loads_embedded_toml_successfully() {
        // The embedded TOML contains placeholder secrets (e.g. "trusted-server",
        // "change-me-proxy-secret"). This is expected — production builds override
        // them via TRUSTED_SERVER__* env vars at build time.
        let settings = get_settings().expect("should load settings from embedded TOML");
        // Verify basic structure is loaded
        assert!(!settings.publisher.domain.is_empty());
        assert!(!settings.publisher.cookie_domain.is_empty());
        assert!(!settings.publisher.origin_url.is_empty());
        assert!(!settings.synthetic.counter_store.is_empty());
        assert!(!settings.synthetic.opid_store.is_empty());
        assert!(!settings.synthetic.secret_key.expose().is_empty());
        assert!(!settings.synthetic.template.is_empty());
    }
}
