use core::str;
use error_stack::{Report, ResultExt};
use validator::Validate;

use crate::error::TrustedServerError;
use crate::settings::{EdgeCookie, Publisher, Settings};

pub use crate::auction_config_types::AuctionConfig;

const SETTINGS_DATA: &[u8] = include_bytes!("../../../target/trusted-server-out.toml");

/// Creates a new [`Settings`] instance from the embedded configuration file.
///
/// Loads the pre-built TOML that was generated by `build.rs` (base config
/// merged with any `TRUSTED_SERVER__` environment variable overrides at
/// build time). Environment variables are **not** read at runtime.
///
/// # Errors
///
/// - [`TrustedServerError::InvalidUtf8`] if the embedded TOML file contains invalid UTF-8
/// - [`TrustedServerError::Configuration`] if the configuration is invalid or missing required fields
pub fn get_settings() -> Result<Settings, Report<TrustedServerError>> {
    let toml_bytes = SETTINGS_DATA;
    let toml_str = str::from_utf8(toml_bytes).change_context(TrustedServerError::InvalidUtf8 {
        message: "embedded trusted-server.toml file".to_string(),
    })?;

    let settings = Settings::from_toml(toml_str)?;

    // Validate the settings
    settings
        .validate()
        .change_context(TrustedServerError::Configuration {
            message: "Failed to validate configuration".to_string(),
        })?;

    if !settings.proxy.certificate_check {
        log::warn!(
            "INSECURE: proxy.certificate_check is disabled — TLS certificates will NOT be verified"
        );
    }

    if EdgeCookie::is_placeholder_secret_key(settings.edge_cookie.secret_key.expose()) {
        log::warn!(
            "INSECURE: edge_cookie.secret_key is set to a default placeholder — \
             HMAC-SHA256 signatures can be forged. \
             Override via TRUSTED_SERVER__EDGE_COOKIE__SECRET_KEY at build time"
        );
    }

    if Publisher::is_placeholder_proxy_secret(settings.publisher.proxy_secret.expose()) {
        log::warn!(
            "INSECURE: publisher.proxy_secret is set to a default placeholder — \
             XChaCha20-Poly1305 encrypted URLs can be decrypted by anyone. \
             Override via TRUSTED_SERVER__PUBLISHER__PROXY_SECRET at build time"
        );
    }

    Ok(settings)
}

#[cfg(test)]
mod tests {
    use crate::error::TrustedServerError;
    use crate::settings::Settings;
    use crate::test_support::tests::crate_test_settings_str;

    /// Builds a TOML string with the given secret values swapped in.
    ///
    /// # Panics
    ///
    /// Panics if the replacement patterns no longer match the test TOML,
    /// which would cause the substitution to silently no-op.
    fn toml_with_secrets(passphrase: &str, proxy_secret: &str) -> String {
        let original = crate_test_settings_str();
        let after_passphrase = original.replace(
            r#"passphrase = "test-secret-key""#,
            &format!(r#"passphrase = "{passphrase}""#),
        );
        assert_ne!(
            after_passphrase, original,
            "should have replaced passphrase value"
        );
        let result = after_passphrase.replace(
            r#"proxy_secret = "unit-test-proxy-secret""#,
            &format!(r#"proxy_secret = "{proxy_secret}""#),
        );
        assert_ne!(
            result, after_passphrase,
            "should have replaced proxy_secret value"
        );
        result
    }

    #[test]
    fn rejects_placeholder_secret_key() {
        let toml = toml_with_secrets("secret-key", "real-proxy-secret");
        let settings = Settings::from_toml(&toml).expect("should parse TOML");
        let err = settings
            .reject_placeholder_secrets()
            .expect_err("should reject placeholder secret_key");
        let root = err.current_context();
        assert!(
            matches!(root, TrustedServerError::InsecureDefault { field } if field.contains("ec.passphrase")),
            "error should mention ec.passphrase, got: {root}"
        );
    }

    #[test]
    fn rejects_placeholder_proxy_secret() {
        let toml = toml_with_secrets("real-secret-key", "change-me-proxy-secret");
        let settings = Settings::from_toml(&toml).expect("should parse TOML");
        let err = settings
            .reject_placeholder_secrets()
            .expect_err("should reject placeholder proxy_secret");
        let root = err.current_context();
        assert!(
            matches!(root, TrustedServerError::InsecureDefault { field } if field.contains("publisher.proxy_secret")),
            "error should mention publisher.proxy_secret, got: {root}"
        );
    }

    #[test]
    fn rejects_both_placeholders_in_single_error() {
        let toml = toml_with_secrets("secret_key", "change-me-proxy-secret");
        let settings = Settings::from_toml(&toml).expect("should parse TOML");
        let err = settings
            .reject_placeholder_secrets()
            .expect_err("should reject both placeholder secrets");
        let root = err.current_context();
        match root {
            TrustedServerError::InsecureDefault { field } => {
                assert!(
                    field.contains("ec.passphrase"),
                    "error should mention ec.passphrase, got: {field}"
                );
                assert!(
                    field.contains("publisher.proxy_secret"),
                    "error should mention publisher.proxy_secret, got: {field}"
                );
            }
            other => panic!("expected InsecureDefault, got: {other}"),
        }
    }

    #[test]
    fn accepts_non_placeholder_secrets() {
        let toml = toml_with_secrets("production-secret-key", "production-proxy-secret");
        let settings = Settings::from_toml(&toml).expect("should parse TOML");
        settings
            .reject_placeholder_secrets()
            .expect("non-placeholder secrets should pass validation");
    }

    /// Smoke-test the full `get_settings()` pipeline (embedded bytes → UTF-8 →
    /// parse → validate → placeholder check).  The build-time TOML ships with
    /// placeholder secrets, so the expected outcome is an [`InsecureDefault`]
    /// error — but reaching that error proves every earlier stage succeeded.
    #[test]
    fn get_settings_rejects_embedded_placeholder_secrets() {
        let err = super::get_settings().expect_err("should reject embedded placeholder secrets");
        assert!(
            matches!(
                err.current_context(),
                TrustedServerError::InsecureDefault { .. }
            ),
            "should fail with InsecureDefault, got: {err}"
        );
    }
}
