use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use edgezero_core::manifest::ManifestLoader;

/// Source file that must stay out of the generated list.
///
/// `migration_guards.rs` holds the banned pattern itself, as the regex literal
/// the guard matches with, so including it would fail the guard on its own
/// text.
const EXCLUDED: &str = "migration_guards.rs";

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    write_default_config_store_id();
    write_migration_guard_sources();
}

/// Keeps every adapter's compiled default synchronized with the repository
/// manifest.
fn write_default_config_store_id() {
    let crate_dir = PathBuf::from(
        env::var("CARGO_MANIFEST_DIR").expect("should receive CARGO_MANIFEST_DIR from Cargo"),
    );
    let manifest_path = crate_dir
        .ancestors()
        .nth(2)
        .expect("should resolve the workspace root from CARGO_MANIFEST_DIR")
        .join("edgezero.toml");
    println!("cargo:rerun-if-changed={}", manifest_path.display());

    let manifest = match ManifestLoader::from_path(&manifest_path) {
        Ok(manifest) => manifest,
        Err(error) => {
            println!(
                "cargo::error=should load EdgeZero manifest at {}: {error}",
                manifest_path.display()
            );
            std::process::exit(1);
        }
    };
    let Some(config_store) = manifest.manifest().stores.config.as_ref() else {
        println!(
            "cargo::error=should declare [stores.config] in EdgeZero manifest at {}",
            manifest_path.display()
        );
        std::process::exit(1);
    };
    let default_store_id = config_store.default_id();
    println!("cargo:rustc-env=TRUSTED_SERVER_DEFAULT_CONFIG_STORE_ID={default_store_id}");
}

/// Lists every Rust source file under `src` for the migration guard, so a
/// file added to or removed from core joins or leaves the guard on its own.
fn write_migration_guard_sources() {
    // Cargo walks a directory named here, so adding, renaming or deleting a
    // source file reruns this script and the guard list follows the tree.
    println!("cargo:rerun-if-changed=src");

    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("should read CARGO_MANIFEST_DIR"));
    let src_dir = manifest_dir.join("src");

    let mut sources = Vec::new();
    collect_rust_sources(&src_dir, &src_dir, &mut sources);
    sources.sort();

    let mut generated = String::from(
        "// Generated by build.rs. Every Rust source file under `src`, so a file\n\
         // added to or removed from core joins or leaves the guard on its own.\n\
         const CHECKED_SOURCES: &[(&str, &str)] = &[\n",
    );
    for relative in &sources {
        let absolute = format!("{}/{relative}", path_literal(&src_dir));
        generated.push_str(&format!(
            "    (\"{relative}\", include_str!(\"{absolute}\")),\n"
        ));
    }
    generated.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("should read OUT_DIR"));
    fs::write(out_dir.join("migration_guard_sources.rs"), generated)
        .expect("should write the migration guard source list");
}

/// Collects every `.rs` file under `dir`, as a path relative to `root` with
/// forward slashes, so the generated file reads the same on every platform.
fn collect_rust_sources(root: &Path, dir: &Path, sources: &mut Vec<String>) {
    let entries = fs::read_dir(dir).expect("should read a source directory");
    for entry in entries {
        let entry = entry.expect("should read a source directory entry");
        let path = entry.path();
        if path.is_dir() {
            collect_rust_sources(root, &path, sources);
            continue;
        }
        if path.extension().is_some_and(|extension| extension == "rs") {
            let relative = path
                .strip_prefix(root)
                .expect("should strip the source root prefix");
            let relative = path_literal(relative);
            if relative != EXCLUDED {
                sources.push(relative);
            }
        }
    }
}

/// Renders a path for a Rust string literal, with forward slashes so a Windows
/// path needs no escaping.
fn path_literal(path: &Path) -> String {
    path.display().to_string().replace('\\', "/")
}
