use core::str;
use error_stack::{Report, ResultExt};
use validator::Validate;

use crate::error::TrustedServerError;
use crate::settings::{Publisher, Settings, Synthetic};

pub use crate::auction_config_types::AuctionConfig;

const SETTINGS_DATA: &[u8] = include_bytes!("../../../target/trusted-server-out.toml");

/// Creates a new [`Settings`] instance from the embedded configuration file.
///
/// Loads the pre-built TOML that was generated by `build.rs` (base config
/// merged with any `TRUSTED_SERVER__` environment variable overrides at
/// build time). Environment variables are **not** read at runtime.
///
/// # Errors
///
/// - [`TrustedServerError::InvalidUtf8`] if the embedded TOML file contains invalid UTF-8
/// - [`TrustedServerError::Configuration`] if the configuration is invalid or missing required fields
pub fn get_settings() -> Result<Settings, Report<TrustedServerError>> {
    let toml_bytes = SETTINGS_DATA;
    let toml_str = str::from_utf8(toml_bytes).change_context(TrustedServerError::InvalidUtf8 {
        message: "embedded trusted-server.toml file".to_string(),
    })?;

    let settings = Settings::from_toml(toml_str)?;

    // Validate the settings
    settings
        .validate()
        .change_context(TrustedServerError::Configuration {
            message: "Failed to validate configuration".to_string(),
        })?;

    // Reject known placeholder values for secrets that feed into cryptographic operations.
    if Synthetic::is_placeholder_secret_key(&settings.synthetic.secret_key) {
        return Err(Report::new(TrustedServerError::InsecureDefault {
            field: "synthetic.secret_key".to_string(),
        }));
    }

    if Publisher::is_placeholder_proxy_secret(&settings.publisher.proxy_secret) {
        return Err(Report::new(TrustedServerError::InsecureDefault {
            field: "publisher.proxy_secret".to_string(),
        }));
    }

    if !settings.proxy.certificate_check {
        log::warn!(
            "INSECURE: proxy.certificate_check is disabled — TLS certificates will NOT be verified"
        );
    }

    Ok(settings)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_default_placeholder_secrets() {
        // The embedded trusted-server.toml ships with placeholder secrets.
        // get_settings() must reject them so a deployment using defaults fails fast.
        let result = get_settings();
        assert!(
            result.is_err(),
            "should reject settings that contain placeholder secret values"
        );
    }
}
