use core::str;
use error_stack::{Report, ResultExt};
use validator::Validate;

use crate::error::TrustedServerError;
use crate::settings::Settings;

pub use crate::auction_config_types::AuctionConfig;

const SETTINGS_DATA: &[u8] = include_bytes!("../../../target/trusted-server-out.toml");

/// Creates a new [`Settings`] instance from the embedded configuration file.
///
/// Loads the pre-built TOML that was generated by `build.rs` (base config
/// merged with any `TRUSTED_SERVER__` environment variable overrides at
/// build time). Environment variables are **not** read at runtime.
///
/// # Errors
///
/// - [`TrustedServerError::InvalidUtf8`] if the embedded TOML file contains invalid UTF-8
/// - [`TrustedServerError::Configuration`] if the configuration is invalid or missing required fields
pub fn get_settings() -> Result<Settings, Report<TrustedServerError>> {
    let toml_bytes = SETTINGS_DATA;
    let toml_str = str::from_utf8(toml_bytes).change_context(TrustedServerError::InvalidUtf8 {
        message: "embedded trusted-server.toml file".to_string(),
    })?;

    let settings = Settings::from_toml(toml_str)?;

    // Validate the settings
    settings
        .validate()
        .change_context(TrustedServerError::Configuration {
            message: "Failed to validate configuration".to_string(),
        })?;

    // Reject known placeholder values for secrets that feed into cryptographic operations.
    settings.reject_placeholder_secrets()?;

    if !settings.proxy.certificate_check {
        log::warn!(
            "INSECURE: proxy.certificate_check is disabled — TLS certificates will NOT be verified"
        );
    }

    Ok(settings)
}

#[cfg(test)]
mod tests {
    use crate::error::TrustedServerError;
    use crate::settings::Settings;
    use crate::test_support::tests::crate_test_settings_str;

    /// Builds a TOML string with the given secret values swapped in.
    fn toml_with_secrets(secret_key: &str, proxy_secret: &str) -> String {
        crate_test_settings_str()
            .replace(
                r#"secret_key = "test-secret-key""#,
                &format!(r#"secret_key = "{secret_key}""#),
            )
            .replace(
                r#"proxy_secret = "unit-test-proxy-secret""#,
                &format!(r#"proxy_secret = "{proxy_secret}""#),
            )
    }

    #[test]
    fn rejects_placeholder_secret_key() {
        let toml = toml_with_secrets("secret-key", "real-proxy-secret");
        let settings = Settings::from_toml(&toml).expect("should parse TOML");
        let err = settings
            .reject_placeholder_secrets()
            .expect_err("should reject placeholder secret_key");
        let root = err.current_context();
        assert!(
            matches!(root, TrustedServerError::InsecureDefault { field } if field.contains("synthetic.secret_key")),
            "error should mention synthetic.secret_key, got: {root}"
        );
    }

    #[test]
    fn rejects_placeholder_proxy_secret() {
        let toml = toml_with_secrets("real-secret-key", "change-me-proxy-secret");
        let settings = Settings::from_toml(&toml).expect("should parse TOML");
        let err = settings
            .reject_placeholder_secrets()
            .expect_err("should reject placeholder proxy_secret");
        let root = err.current_context();
        assert!(
            matches!(root, TrustedServerError::InsecureDefault { field } if field.contains("publisher.proxy_secret")),
            "error should mention publisher.proxy_secret, got: {root}"
        );
    }

    #[test]
    fn rejects_both_placeholders_in_single_error() {
        let toml = toml_with_secrets("secret_key", "change-me-proxy-secret");
        let settings = Settings::from_toml(&toml).expect("should parse TOML");
        let err = settings
            .reject_placeholder_secrets()
            .expect_err("should reject both placeholder secrets");
        let root = err.current_context();
        match root {
            TrustedServerError::InsecureDefault { field } => {
                assert!(
                    field.contains("synthetic.secret_key"),
                    "error should mention synthetic.secret_key, got: {field}"
                );
                assert!(
                    field.contains("publisher.proxy_secret"),
                    "error should mention publisher.proxy_secret, got: {field}"
                );
            }
            other => panic!("expected InsecureDefault, got: {other}"),
        }
    }

    #[test]
    fn accepts_non_placeholder_secrets() {
        let toml = toml_with_secrets("production-secret-key", "production-proxy-secret");
        let settings = Settings::from_toml(&toml).expect("should parse TOML");
        settings
            .reject_placeholder_secrets()
            .expect("non-placeholder secrets should pass validation");
    }
}
