#!/bin/bash
# Test RSC streaming with LIVE HTML from running Next.js server
#
# Prerequisites: Next.js server must be running on localhost:3099
# Usage: ./test-live-html.sh [url]
#
# This script:
# 1. Fetches HTML from your running Next.js server
# 2. Processes it through trusted-server pipeline
# 3. Shows streaming metrics and verifies RSC rewriting

set -e

PORT=3099
URL=${1:-"http://localhost:$PORT/"}
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

cleanup() {
    rm -f "${TEST_FILE:-}" "${TEMP_FIXTURE:-}"
}
trap cleanup EXIT

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         LIVE RSC STREAMING TEST                            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo

# Check if server is running
if ! curl -s "$URL" > /dev/null 2>&1; then
    echo "❌ Next.js server not running on $URL"
    echo
    echo "Start it first with:"
    echo "  cd examples/nextjs-rsc-app"
    echo "  npm run dev    # or npm run start"
    exit 1
fi

echo "✅ Server is running at $URL"
echo

# Fetch HTML
echo "📥 Fetching HTML from live server..."
HTML=$(curl -s "$URL")
SIZE=$(echo "$HTML" | wc -c | tr -d ' ')
echo "   Downloaded: $SIZE bytes"
echo

# Analyze raw HTML
RSC_COUNT=$(echo "$HTML" | grep -c "__next_f.push" || echo "0")
ORIGIN_COUNT=$(echo "$HTML" | grep -o "origin.example.com" | wc -l | tr -d ' ')

echo "📊 Raw HTML Analysis:"
echo "   RSC scripts: $RSC_COUNT"
echo "   origin.example.com occurrences: $ORIGIN_COUNT"

if [ "$RSC_COUNT" -eq 0 ]; then
    echo "   ⚠️  No RSC content found - this might not be an RSC page"
fi
echo

# Save to temp fixture for processing
TEMP_FIXTURE="$PROJECT_ROOT/crates/common/src/integrations/nextjs/fixtures/live-test.html"
echo "$HTML" > "$TEMP_FIXTURE"
echo "💾 Saved to temp fixture: live-test.html"
echo

# Create a test that uses this fixture
TEST_FILE="$PROJECT_ROOT/crates/common/tests/test_live_html.rs"
cat > "$TEST_FILE" << 'RUST_TEST_EOF'
//! Test live HTML from running Next.js server
//! This file is auto-generated by test-live-html.sh

use trusted_server_common::html_processor::{create_html_processor, HtmlProcessorConfig};
use trusted_server_common::integrations::IntegrationRegistry;
use trusted_server_common::settings::Settings;
use trusted_server_common::streaming_processor::StreamProcessor;

fn create_test_settings() -> Settings {
    let toml = r#"
        [[handlers]]
        path = "^/secure"
        username = "user"
        password = "pass"

        [publisher]
        domain = "test-publisher.com"
        cookie_domain = ".test-publisher.com"
        origin_backend = "publisher_origin"
        origin_url = "https://origin.example.com"
        proxy_secret = "unit-test-proxy-secret"

        [integrations.prebid]
        enabled = false

        [integrations.nextjs]
        enabled = true
        rewrite_attributes = ["href", "link", "url"]

        [synthetic]
        counter_store = "test-counter-store"
        opid_store = "test-opid-store"
        secret_key = "test-secret-key"
        template = "{{client_ip}}:{{user_agent}}"

        [request_signing]
        config_store_id = "test-config-store-id"
        secret_store_id = "test-secret-store-id"

        [[backends]]
        name = "publisher_origin"
        target = "https://origin.example.com"
    "#;
    Settings::from_toml(toml).expect("test settings should parse")
}

#[test]
fn test_live_html_streaming() {
    let html = include_str!("../src/integrations/nextjs/fixtures/live-test.html");

    println!("\n╔════════════════════════════════════════════════════════════╗");
    println!("║              PROCESSING LIVE HTML                          ║");
    println!("╚════════════════════════════════════════════════════════════╝\n");

    let settings = create_test_settings();
    let registry = IntegrationRegistry::new(&settings).expect("Failed to create registry");
    let config = HtmlProcessorConfig::from_settings(
        &settings,
        &registry,
        "origin.example.com",
        "trusted.example.com",
        "https",
    );

    // Test with different chunk sizes
    for &chunk_size in &[32, 64, 256, 8192] {
        let mut processor = create_html_processor(config.clone());
        let mut intermediate = 0;
        let mut final_bytes = 0;
        let mut output = Vec::new();

        let total_chunks = (html.len() + chunk_size - 1) / chunk_size;
        for (i, chunk) in html.as_bytes().chunks(chunk_size).enumerate() {
            let is_last = i == total_chunks - 1;
            let result = processor.process_chunk(chunk, is_last).unwrap();

            if is_last {
                final_bytes = result.len();
            } else {
                intermediate += result.len();
            }
            output.extend_from_slice(&result);
        }

        let total = intermediate + final_bytes;
        let ratio = if total > 0 {
            (intermediate as f64 / total as f64) * 100.0
        } else {
            0.0
        };

        println!("Chunk size {:5}B: {:5.1}% streamed ({} intermediate, {} final)",
            chunk_size, ratio, intermediate, final_bytes);

        // For 64-byte chunks, verify RSC rewriting
        if chunk_size == 64 {
            let output_str = String::from_utf8_lossy(&output);

            // Count origin URLs in RSC scripts
            let rsc_origin_count: usize = output_str
                .split("<script>")
                .filter(|s| s.contains("__next_f.push"))
                .map(|s| s.matches("origin.example.com").count())
                .sum();

            println!("\n🔍 RSC Payload Verification (64B chunks):");
            println!("   Origin URLs in RSC payloads: {}", rsc_origin_count);

            if rsc_origin_count == 0 {
                println!("   ✅ All RSC payload URLs successfully rewritten!");
            } else {
                println!("   ⚠️  {} origin URLs remain (may indicate fragmentation)", rsc_origin_count);
            }
        }
    }

    println!("\n╔════════════════════════════════════════════════════════════╗");
    println!("║                  TEST COMPLETE                             ║");
    println!("╚════════════════════════════════════════════════════════════╝");
}
RUST_TEST_EOF

echo "🧪 Running test with live HTML..."
cd "$PROJECT_ROOT"
cargo test --test test_live_html -- --nocapture

# Cleanup
echo
echo "✅ Test complete!"
