// Auto-generated by build-all.mjs — manual edits will be overwritten at build time.
//
// Controls which Prebid.js user ID modules are included in the bundle.
// Set the TSJS_PREBID_USER_ID_MODULES environment variable to a comma-separated
// list of module names (e.g. "connectId,criteo,sharedId") before building.
// Default: ""

