// Auto-generated by build-all.mjs — manual edits will be overwritten at build time.
//
// Controls which Prebid.js User ID submodules are included in the bundle.
// Set the TSJS_PREBID_USER_IDS environment variable to a comma-separated
// list of submodule filenames without the `.js` extension
// (e.g. "sharedIdSystem,id5IdSystem,criteoIdSystem") before building.
// The userId.js core module is always included via a static import in
// index.ts and is not configurable here.

import 'prebid.js/modules/sharedIdSystem.js';
import 'prebid.js/modules/criteoIdSystem.js';
import 'prebid.js/modules/33acrossIdSystem.js';
import 'prebid.js/modules/pubProvidedIdSystem.js';
import 'prebid.js/modules/quantcastIdSystem.js';
import 'prebid.js/modules/id5IdSystem.js';
import 'prebid.js/modules/identityLinkIdSystem.js';
import 'prebid.js/modules/uid2IdSystem.js';
import 'prebid.js/modules/euidIdSystem.js';
import 'prebid.js/modules/intentIqIdSystem.js';
import 'prebid.js/modules/lotamePanoramaIdSystem.js';
import 'prebid.js/modules/connectIdSystem.js';
import 'prebid.js/modules/merkleIdSystem.js';
