// Auto-generated by build-all.mjs — manual edits will be overwritten at build time.
//
// Controls which Prebid.js User ID modules are included in the bundle.
// Set the TSJS_PREBID_USER_ID_MODULES environment variable to a comma-separated list
// of module names (e.g. "sharedId,pubProvided,uid2") before building.
// Default: empty
