// Auto-generated by build-all.mjs — manual edits will be overwritten at build time.
//
// Deterministic Prebid.js user ID module preset for attested builds.
// TSJS_PREBID_USER_ID_MODULES is intentionally ignored in production builds.
// Use TSJS_PREBID_USER_ID_MODULES_DEV_OVERRIDE only for local experiments.
// Modules: connectIdSystem, criteoIdSystem, id5IdSystem, identityLinkIdSystem, liveIntentIdSystem, pubProvidedIdSystem, sharedIdSystem, uid2IdSystem, unifiedIdSystem

import 'prebid.js/modules/connectIdSystem.js';
import 'prebid.js/modules/criteoIdSystem.js';
import 'prebid.js/modules/id5IdSystem.js';
import 'prebid.js/modules/identityLinkIdSystem.js';
import 'prebid.js/modules/liveIntentIdSystem.js';
import 'prebid.js/modules/pubProvidedIdSystem.js';
import 'prebid.js/modules/sharedIdSystem.js';
import 'prebid.js/modules/uid2IdSystem.js';
import 'prebid.js/modules/unifiedIdSystem.js';
